services:
  web:
    ports: !reset []
    mem_limit: 512m
    cpus: 0.75
    networks:
      meet.jitsi: {}
      caddy:
        aliases: [raero-jitsi-web]
  prosody:
    mem_limit: 512m
    cpus: 0.75
  jicofo:
    ports: !reset []
    mem_limit: 768m
    cpus: 1
  jvb:
    ports: !override
      - "10000:10000/udp"
    mem_limit: 1536m
    cpus: 2
networks:
  caddy:
    external: true
    name: caddy_default
