import assert from 'node:assert/strict';import {suite,origin,output,t} from './harness.mjs';
await suite('admin-content',async({page,step})=>{
 const a=await page('admin'),p=await page();a.on('dialog',d=>d.accept());
 await a.goto(origin+'/admin?tab=faq');if(!process.env.RAERO_E2E_RESUME){await a.getByPlaceholder(t['adminFaq.question'],{exact:true}).fill('Question de recette E2E ?');await a.getByPlaceholder(t['adminFaq.answer'],{exact:true}).fill('Réponse synthétique pour vérifier la publication.');await a.getByRole('button',{name:t['adminFaq.add'],exact:true}).click();await a.getByText(t['adminFaq.created'],{exact:true}).waitFor();
 }await p.goto(origin+'/#faq');await p.getByText('Réponse synthétique pour vérifier la publication.',{exact:true}).waitFor({state:'attached'});await p.getByText('Réponse synthétique pour vérifier la publication.',{exact:true}).locator('xpath=ancestor::details').locator('summary').click();await p.getByText('Réponse synthétique pour vérifier la publication.',{exact:true}).waitFor();step('admin FAQ creation renders on landing and expands');
 const faq=a.locator('div.rounded-xl').filter({has:a.locator('input[value="Question de recette E2E ?"]')});await faq.locator('textarea').fill('Réponse modifiée par la recette.');await faq.locator('textarea').blur();await a.getByText(t['adminFaq.saved'],{exact:true}).waitFor();await faq.getByRole('button',{name:t['adminFaq.active'],exact:true}).click();await faq.getByRole('button',{name:t['adminFaq.inactive'],exact:true}).waitFor();await p.reload();assert.equal(await p.getByText('Question de recette E2E ?',{exact:true}).count(),0);step('FAQ edit and visibility toggle');
 await faq.getByRole('button').last().click();await a.getByText(t['adminFaq.deleted'],{exact:true}).waitFor();step('test FAQ deletion');
 await a.goto(origin+'/admin?tab=news');await a.getByRole('button',{name:t['adminArticles.newArticle'],exact:true}).click();const dialog=a.getByRole('dialog');await dialog.getByPlaceholder(t['adminArticles.placeholderTitle'],{exact:true}).fill('Recette E2E aéronautique');await dialog.getByPlaceholder(t['adminArticles.placeholderExcerpt'],{exact:true}).fill('Article synthétique pour vérifier les actualités.');await dialog.getByPlaceholder(t['adminArticles.placeholderContent'],{exact:true}).fill('Contenu de recette : préparation, contrôle et traçabilité des opérations.');await dialog.getByRole('button',{name:t['adminArticles.save'],exact:true}).click();await dialog.waitFor({state:'hidden'});
 await p.goto(origin+'/actualites/recette-e2e-aeronautique');await p.getByRole('heading',{name:'Recette E2E aéronautique',exact:true}).waitFor();await p.getByText('Contenu de recette : préparation, contrôle et traçabilité des opérations.',{exact:false}).waitFor();step('published article renders publicly');
 const article=a.locator('div.flex.items-center.gap-3.p-3').filter({hasText:'Recette E2E aéronautique'});await article.getByRole('button').last().click();await a.getByText(t['adminArticles.toastDeleted'],{exact:true}).waitFor();step('test article deletion');
 await a.goto(origin+'/admin?tab=offers');await a.getByPlaceholder(t['adminOffers.name'],{exact:true}).fill('Offre de recette');await a.getByPlaceholder(t['adminOffers.description'],{exact:true}).first().fill('Offre synthétique de recette');await a.getByPlaceholder(t['adminOffers.price'],{exact:true}).first().fill('Sur devis');await a.getByPlaceholder(t['adminOffers.ctaLabel'],{exact:true}).first().fill('Contacter');await a.getByPlaceholder(t['adminOffers.ctaHref'],{exact:true}).first().fill('/devis');await a.getByRole('button',{name:t['adminOffers.add'],exact:true}).click();await a.getByText(t['adminOffers.created'],{exact:true}).waitFor();step('admin creates managed offer');await a.screenshot({path:`${output}/admin-offers.png`,fullPage:true});
});
