import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {suite,origin,output,t,credentials} from './harness.mjs';
await suite('company',async({page,step})=>{
 const p=await page('manager');
 if(!process.env.RAERO_E2E_RESUME){
 await p.goto(origin+'/entreprise?tab=members');await p.getByPlaceholder(t['companyMembers.emailPlaceholder']).fill(credentials.learnerEmail);await p.getByRole('button',{name:t['companyMembers.add'],exact:true}).click();await p.getByText(credentials.learnerEmail,{exact:true}).waitFor();step('manager affiliates existing learner');
 await p.goto(origin+'/entreprise?tab=employees');await p.getByRole('button',{name:t['companyDashboard.addEmployee'],exact:true}).click();let dialog=p.getByRole('dialog');
 for(const [placeholder,value] of [['Jean','Recette'],['Dupont','Apprenant'],['jean.dupont@mro.com',credentials.learnerEmail],['Technicien B1','Technicien B1'],['B1.1, B1.3','B1.1'],['Line Maintenance','Maintenance'],['CDG','CDG']])await dialog.getByPlaceholder(placeholder,{exact:true}).fill(value);
 await dialog.getByRole('button',{name:t['companyDashboard.add'],exact:true}).click();await dialog.waitFor({state:'hidden'});await p.getByRole('cell',{name:credentials.learnerEmail,exact:true}).waitFor();step('employee dossier created and linked to learner');
 await p.getByRole('button',{name:t['companyDashboard.importCsv'],exact:true}).click();dialog=p.getByRole('dialog');await dialog.locator('input[type=file]').setInputFiles({name:'recette-employees.csv',mimeType:'text/csv',buffer:Buffer.from('prenom;nom;email;fonction;licence;categories;typeratings;departement;base\nCamille;Recette;camille-e2e@example.test;Technicien B1;TEST66;B1.1;;Maintenance;ORY\n')});await dialog.getByRole('button',{name:t['companyDashboard.csvStartImport'],exact:true}).click();await dialog.getByText('1 employé(s) importé(s) avec succès',{exact:true}).waitFor();await dialog.getByRole('button',{name:t['companyDashboard.close'],exact:true}).click();await p.getByRole('cell',{name:'camille-e2e@example.test',exact:true}).waitFor();step('employee CSV import through file picker');
 await p.goto(origin+'/entreprise?tab=conformite');await p.locator('#rule-label').fill('Recette — contrôle périodique');await p.locator('#rule-training').selectOption({label:'Recette complète — Maintenance aéronautique'});await p.locator('#rule-jobTitleContains').fill('Technicien');await p.locator('#rule-period').fill('24');await p.getByRole('button',{name:t['companyDashboard.addRule'],exact:true}).click();await p.getByText('Recette — contrôle périodique',{exact:true}).waitFor();await p.getByRole('button',{name:t['companyDashboard.runTna'],exact:true}).click();await p.getByText(/\d+ suivi.*créé/i).first().waitFor();step('training requirement created and TNA generates employee follow-up');
 }
 await p.goto(origin+'/entreprise?tab=recurrencies');await p.getByRole('cell',{name:'Recette complète — Maintenance aéronautique',exact:true}).first().waitFor();const downloaded=p.waitForEvent('download');await p.getByRole('button',{name:t['companyDashboard.exportAllRecurrencies'],exact:true}).click();await(await downloaded).saveAs(`${output}/company-recurrencies.csv`);assert.ok(fs.readFileSync(`${output}/company-recurrencies.csv`,'utf8').includes('Recette complète'));step('company recurrence tracking and CSV export');
 if(!process.env.RAERO_E2E_RESUME){await p.goto(origin+'/catalogue');await p.locator('#catalogue-search').fill('Recette complète');await p.locator('a[href^="/formation/"]').first().click();await p.getByRole('button',{name:t['trainingDetail.addToCart'],exact:true}).click();await p.getByText(/ajoutée? au panier/i).first().waitFor();}await p.goto(origin+'/checkout');await p.locator('select').selectOption({label:'Recette Aero MRO'});
 await p.route('**/__e2e/checkout?**',route=>route.fulfill({contentType:'text/html',body:'<h1>Paiement entreprise simulé</h1>'}));await p.getByRole('button',{name:/^Payer /}).click();await p.waitForURL('**/__e2e/checkout?**');const id=new URL(p.url()).searchParams.get('session_id');const payment=JSON.parse(execFileSync('docker',['exec','--user','node',process.env.RAERO_E2E_CONTAINER||'raero-e2e-simulation-20260923','node','/app/scripts/e2e/stripe-control.mjs','pay',id],{encoding:'utf8'}));await p.goto(payment.successUrl);await p.getByText(t['dashboard.toastPaymentConfirmed'],{exact:true}).waitFor();step('company buys a seat through simulated signed payment');
 await p.goto(origin+'/cart');await p.getByText(t['cart.emptyTitle'],{exact:true}).waitFor();step('paid cart is empty after server fulfillment');
 await p.goto(origin+'/licences');await p.getByRole('button',{name:t['licenses.assign'],exact:true}).first().click();await p.locator('select').selectOption({label:'Recette Apprenant'});await p.getByRole('button',{name:t['licenses.assign'],exact:true}).first().click();await p.getByText(t['licenses.assigned'],{exact:true}).last().waitFor();await p.getByText(/Attribuées.*Recette Apprenant/i).waitFor();step('manager assigns purchased seat to affiliated learner');
 await p.screenshot({path:`${output}/company-license.png`,fullPage:true});
});
