import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright-core';
const origin=process.env.RAERO_E2E_ORIGIN||'http://127.0.0.1:3177',output=process.env.RAERO_E2E_OUTPUT||'tmp/e2e/simulation',t=JSON.parse(fs.readFileSync('client/src/locales/fr.json','utf8'));
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({storageState:`${output}/learner-state.json`,viewport:{width:1440,height:1000}}),page=await context.newPage();context.setDefaultTimeout(20000);const report=[];
try{
 await page.goto(origin+'/dashboard?tab=certificates');await page.getByText('Recette complète — Maintenance aéronautique',{exact:true}).waitFor();
 const pdf=await page.getByRole('link',{name:'PDF',exact:true}).getAttribute('href');const response=await context.request.get(origin+pdf);assert.equal(response.status(),200);assert.ok((await response.body()).subarray(0,4).equals(Buffer.from('%PDF')));fs.writeFileSync(`${output}/certificate.pdf`,await response.body());report.push('issued certificate PDF is downloadable by its owner');
 const anonymous=await browser.newContext();assert.equal((await anonymous.request.get(origin+pdf)).status(),404);report.push('certificate file rejects anonymous access');
 const verify=await page.locator('a[href^="/verification/"]').getAttribute('href'),publicPage=await anonymous.newPage();await publicPage.goto(origin+verify);await publicPage.getByText(t['certificateVerification.validBanner'],{exact:true}).waitFor();await publicPage.screenshot({path:`${output}/certificate-verification.png`,fullPage:true});report.push('certificate authenticity can be verified publicly');
 await page.goto(origin+'/dashboard?tab=orders');await page.getByRole('button',{name:t['dashboard.btnViewInvoice'],exact:true}).first().click();const form=page.getByRole('dialog');
 await form.getByLabel('Adresse de facturation complète',{exact:true}).fill('1 avenue des essais, 75000 Paris');await form.getByLabel('Pays (code à deux lettres)',{exact:true}).fill('FR');
 const invoiceResponse=page.waitForResponse(r=>r.url().includes('checkout.generateInvoice')&&r.request().method()==='POST');await form.getByRole('button',{name:'Émettre la facture',exact:true}).click();const invoice=await(await invoiceResponse).json();const result=(Array.isArray(invoice)?invoice[0]:invoice).result.data.json;assert.ok(result.url);
 const invoicePdf=await context.request.get(origin+result.url);assert.equal(invoicePdf.status(),200);assert.ok((await invoicePdf.body()).subarray(0,4).equals(Buffer.from('%PDF')));fs.writeFileSync(`${output}/invoice.pdf`,await invoicePdf.body());report.push('invoice generated from synthetic legal issuer and billing details');
 assert.equal((await anonymous.request.get(origin+result.url)).status(),404);report.push('invoice rejects anonymous access');
 await page.getByRole('dialog').locator('iframe').waitFor();await page.screenshot({path:`${output}/invoice-preview.png`,fullPage:true});
 fs.writeFileSync(`${output}/documents.json`,JSON.stringify({certificateUrl:pdf,verificationPath:verify,invoiceUrl:result.url},null,2));fs.writeFileSync(`${output}/documents-results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(error){await page.screenshot({path:`${output}/documents-failure.png`,fullPage:true});fs.writeFileSync(`${output}/documents-failure.txt`,await page.locator('body').innerText());throw error;}finally{await browser.close();}
