import fs from 'node:fs';import assert from 'node:assert/strict';import {suite,origin,output,t} from './harness.mjs';
await suite('final-ui',async({page,step})=>{
 const {trainingId}=JSON.parse(fs.readFileSync(`${output}/course.json`,'utf8'));
 for(const [role,route] of [['learner','/dashboard?tab=orders'],['manager','/entreprise?tab=conformite'],['admin','/admin?tab=quotes'],['author',`/maker/${trainingId}`]]){
  const p=await page(role);await p.setViewportSize({width:390,height:844});await p.goto(origin+route);await p.locator('.app-language-switcher').waitFor();
  for(const lang of ['fr','en','ar']){await p.locator('.app-language-switcher button').filter({hasText:lang.toUpperCase()}).click();await p.waitForFunction(l=>document.documentElement.lang===l,lang);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${role} ${lang} overflows`);assert.equal(await p.locator('html').getAttribute('dir'),lang==='ar'?'rtl':'ltr');await p.screenshot({path:`${output}/final-${role}-${lang}-mobile.png`});}step(`${role} mobile fits in French, English and Arabic RTL`);
 }
 const p=await page('learner');for(const width of [1440,390]){await p.setViewportSize({width,height:1000});await p.goto(origin+'/dashboard?tab=orders');await p.getByRole('button',{name:t['dashboard.btnPreview'],exact:true}).first().click();const iframe=p.getByRole('dialog').locator('iframe');await iframe.waitFor();const src=await iframe.getAttribute('src');assert.ok(src.includes('preview=1'));const response=await p.context().request.get(src);assert.equal(response.headers()['content-disposition'].startsWith('inline'),true);assert.equal((await response.body()).subarray(0,5).toString(),'%PDF-');await p.waitForTimeout(1500);const box=await p.getByRole('dialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);await p.screenshot({path:`${output}/final-pdf-${width}.png`});await p.keyboard.press('Escape');await p.getByRole('dialog').waitFor({state:'hidden'});await p.waitForFunction(label=>document.activeElement?.textContent?.trim()===label,t['dashboard.btnPreview']);}step('real PDF viewer loads inline on desktop and mobile');
});
