import fs from 'node:fs';import assert from 'node:assert/strict';import {suite,origin,output,t} from './harness.mjs';
await suite('live',async({page,step})=>{
 const a=await page('admin'),p=await page('learner');
 await a.goto(origin+'/admin?tab=trainings');await a.getByRole('button',{name:t['adminDashboard.subTabSessions'],exact:true}).click();await a.getByRole('button',{name:'Créer un webinaire',exact:true}).click();let dialog=a.getByRole('dialog');await dialog.locator('#webinar-title').fill('Webinaire de recette E2E');
 const start=await a.evaluate(()=>{const d=new Date(Date.now()+300000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);});await dialog.locator('#webinar-start').fill(start);
 const created=a.waitForResponse(r=>r.url().includes('admin.webinars.create'));await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click();const raw=await(await created).json();const webinar=(Array.isArray(raw)?raw[0]:raw).result.data.json;fs.writeFileSync(`${output}/webinar.json`,JSON.stringify(webinar,null,2));await dialog.waitFor({state:'hidden'});step('administrator schedules a public webinar');
 await p.goto(origin+'/webinars');const card=p.locator('div.rounded-xl').filter({has:p.getByRole('heading',{name:'Webinaire de recette E2E',exact:true})});await card.getByRole('button',{name:t['webinars.register'],exact:true}).click();await p.getByText(t['webinars.registerSuccess'],{exact:true}).waitFor();step('learner reserves webinar');
 const row=a.getByRole('row').filter({hasText:'Webinaire de recette E2E'});await row.getByRole('button',{name:'Statut',exact:true}).click();dialog=a.getByRole('dialog');await dialog.locator('#webinar-status').selectOption('live');await dialog.locator('#webinar-reason').fill('Démarrage de la classe de recette');await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click();await dialog.waitFor({state:'hidden'});
 await p.reload();await card.getByRole('button',{name:t['webinars.joinLive'],exact:true}).click();await p.waitForURL('**/live/webinar/*');const livePath=new URL(p.url()).pathname;await a.goto(origin+livePath);await p.getByPlaceholder(t['liveRoom.messagePlaceholder']).fill('Bonjour depuis le compte apprenant de recette.');await p.getByRole('button',{name:t['liveRoom.sendMessage'],exact:true}).click();await a.getByText('Bonjour depuis le compte apprenant de recette.',{exact:true}).waitFor();step('live chat reaches moderator');
 await a.getByRole('button',{name:t['liveRoom.tabPolls'],exact:true}).click();await a.getByRole('button',{name:t['liveRoom.launchPollQuiz'],exact:true}).click();await a.getByPlaceholder(t['liveRoom.questionInputPlaceholder'],{exact:true}).fill('Quel contrôle précède une intervention ?');await a.getByPlaceholder(t['liveRoom.optionPlaceholder'].replace('{num}','1'),{exact:true}).fill('Consulter la procédure');await a.getByPlaceholder(t['liveRoom.optionPlaceholder'].replace('{num}','2'),{exact:true}).fill('Ignorer la procédure');await a.getByRole('button',{name:t['liveRoom.launch'],exact:true}).click();
 await p.getByRole('button',{name:t['liveRoom.tabPolls'],exact:true}).click();await p.getByRole('button',{name:/Consulter la procédure/}).click();await p.getByText(/Réponse enregistrée|Choix enregistré/).waitFor();await a.getByText(/100% \(1\)/).waitFor();await a.getByRole('button',{name:t['liveRoom.closeVote'],exact:true}).click();await a.getByText(t['liveRoom.closed'],{exact:true}).waitFor();step('moderator launches poll, learner votes, results and closure persist');
 await p.getByRole('button',{name:t['liveRoom.tabQa'],exact:true}).click();await p.getByPlaceholder(t['liveRoom.questionPlaceholder']).fill('Où retrouver les documents après la session ?');await p.getByRole('button',{name:t['liveRoom.sendMessage'],exact:true}).click();await a.getByRole('button',{name:t['liveRoom.tabQa'],exact:true}).click();await a.getByText('Où retrouver les documents après la session ?',{exact:true}).waitFor();step('live Q&A reaches moderator');
 await a.getByRole('button',{name:t['liveRoom.tabScore'],exact:true}).click();await a.getByText('Recette Apprenant',{exact:true}).waitFor();step('attendance and engagement displayed');
 await p.screenshot({path:`${output}/live-learner.png`,fullPage:true});await a.screenshot({path:`${output}/live-moderator.png`,fullPage:true});
});
