import fs from 'node:fs';import assert from 'node:assert/strict';import {suite,origin,output,t} from './harness.mjs';
await suite('passport',async({page,step,browser})=>{
 const p=await page('learner');await p.goto(origin+'/dashboard?tab=id');if(!process.env.RAERO_E2E_RESUME){await p.getByRole('tab',{name:t['passport.tabFormation'],exact:true}).click();await p.getByRole('button',{name:t['passport.addDocument'],exact:true}).click();const dialog=p.getByRole('dialog');
 await dialog.getByLabel(t['passport.fieldTitle'],{exact:true}).fill('Document synthétique de recette');await dialog.getByLabel(t['passport.fieldIssuer'],{exact:true}).fill('Organisme fictif de recette');await dialog.locator('input[type=file]').setInputFiles(`${output}/certificate.pdf`);await dialog.getByRole('button',{name:t['passport.save'],exact:true}).click();await dialog.waitFor({state:'hidden'});await p.getByText('Document synthétique de recette',{exact:false}).waitFor();step('passport document uploaded and listed');
 const row=p.locator('div.flex.items-center.gap-3.p-3').filter({hasText:'Document synthétique de recette'});const url=await row.getByTitle(t['passport.view']).getAttribute('href');assert.equal((await p.context().request.get(origin+url)).status(),200);const anonymous=await browser.newContext();assert.equal((await anonymous.request.get(origin+url)).status(),404);step('passport document owner access and anonymous denial');
 p.once('dialog',d=>d.accept());await row.getByTitle(t['passport.delete']).click();await p.getByRole('tab',{name:t['passport.archives'],exact:true}).click();await p.getByText('Document synthétique de recette',{exact:false}).first().waitFor();step('document archived with retained audit history');
 }p.on('dialog',d=>d.accept());await p.getByRole('tab',{name:t['passport.tabCompliance'],exact:true}).click();await p.getByLabel(/^Certificat/).selectOption({index:1});await p.getByLabel(/^Compagnie destinataire/).selectOption({label:'Recette Aero MRO'});await p.getByRole('button',{name:'Partager le certificat',exact:true}).click();await p.getByRole('button',{name:'Retirer le partage',exact:true}).waitFor();step('learner shares independent certificate with affiliated company');
 await p.getByRole('button',{name:'Retirer le partage',exact:true}).click();await p.getByText('Historique du partage',{exact:true}).click();await p.getByText(/Retrait ·/).waitFor();step('learner withdraws sharing and history remains available');
 await p.screenshot({path:`${output}/passport-compliance.png`,fullPage:true});
});
