import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {suite,origin,output,t,credentials} from './harness.mjs';
const email='security-ui-e2e@example.test';
function mail(){return JSON.parse(execFileSync('docker',['exec','--user','node',process.env.RAERO_E2E_CONTAINER||'raero-e2e-simulation-20260923','cat','/tmp/raero-e2e-mail.json'],{encoding:'utf8'})).filter(m=>m.to===email).at(-1);}
const code=()=>{const match=mail().html.match(/>(\d{6})</);assert.ok(match);return match[1];};
await suite('security',async({page,step})=>{
 const p=await page();await p.goto(origin+'/register');await p.locator('#reg-field-1').fill('Recette Sécurité');await p.locator('#reg-field-2').fill(email);await p.locator('#reg-field-3').fill(credentials.password);await p.locator('form button[type=submit]').click();await p.waitForURL('**/dashboard');step('separate security account registered');
 await p.goto(origin+'/profil');const resetResponse=p.waitForResponse(r=>r.url().includes('auth.requestPasswordReset'));await p.getByRole('button',{name:t['userProfile.passwordButton'],exact:true}).click();await resetResponse;const reset=mail().html.match(/href="([^"]*reset-password\?token=[^"]+)"/);assert.ok(reset);const resetUrl=reset[1].replaceAll('&amp;','&');
 await p.goto(resetUrl);await p.locator('input[type=password]').nth(0).fill(credentials.password+'New');await p.locator('input[type=password]').nth(1).fill(credentials.password+'New');await p.locator('form button[type=submit]').click();await p.getByText(t['resetPassword.success'],{exact:true}).waitFor();step('password recovery via captured local email link');
 await p.goto(origin+'/login');await p.locator('#login-field-2').fill(email);await p.locator('#login-password').fill(credentials.password+'New');await p.locator('form button[type=submit]').click();await p.waitForURL('**/dashboard');step('new password signs in');
 await p.goto(origin+'/profil');await p.getByRole('button',{name:'Activer',exact:true}).click();await p.locator('#two-factor-password').fill(credentials.password+'New');const begin=p.waitForResponse(r=>r.url().includes('auth.beginTwoFactorChange'));await p.getByRole('button',{name:'Recevoir le code',exact:true}).click();await begin;await p.locator('#two-factor-code').fill(code());await p.getByRole('button',{name:'Confirmer le changement',exact:true}).click();await p.getByRole('button',{name:'Désactiver',exact:true}).waitFor();step('email two-factor activation requires password and captured code');
 const second=await page();await second.goto(origin+'/login');await second.locator('#login-field-2').fill(email);await second.locator('#login-password').fill(credentials.password+'New');const login=second.waitForResponse(r=>r.url().includes('auth.login'));await second.locator('form button[type=submit]').click();await login;await second.locator('input[inputmode=numeric]').fill(code());await second.locator('form button[type=submit]').click();await second.waitForURL('**/dashboard');step('independent browser login requires second factor');
 await p.locator('#session-password').fill(credentials.password+'New');await p.getByRole('button',{name:'Déconnecter tous mes appareils',exact:true}).click();await p.waitForURL('**/login');await second.reload();await second.getByText(t['dashboard.loginRequiredTitle'],{exact:true}).waitFor();step('revoke all sessions invalidates both browsers');
});
