import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { useI18n } from "@/i18n";
import { trpc } from "@/lib/trpc";
import PublicNav from "@/components/PublicNav";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { toast } from "sonner";
const copy = {
  fr: { title: "Abonnements compagnie", intro: "Choisissez la compagnie dont vous gérez la facturation.", choose: "Compagnie", empty: "Aucune compagnie active à gérer.", login: "Connectez-vous pour gérer vos abonnements.", load: "Chargement…", status: "Statut de facturation", none: "Aucun abonnement actif", seats: "Salariés actifs / places payées", unlimited: "Sans limite par salarié", due: "Fin de période vérifiée", review: "Rapprochement nécessaire. Actualisez le statut ou contactez l’assistance.", over: "Les places vérifiées ne couvrent pas tout l’effectif actif. Les accès liés à cet abonnement sont suspendus jusqu’à régularisation.", portal: "Ouvrir le portail de facturation", refresh: "Actualiser l’abonnement", updated: "Statut de facturation actualisé.", standard: "Standard — par salarié actif", all: "All Inclusive — forfait compagnie", terms: "Le tarif, les taxes et la périodicité sont présentés dans Stripe avant votre confirmation. Standard couvre l’ensemble de l’effectif actif.", existing: "Un abonnement est déjà rattaché. Gérez-le dans le portail ; contactez l’assistance pour un remplacement.", support: "Contacter l’assistance", back: "Mon espace", returned: "De retour de Stripe : actualisez l’abonnement pour vérifier son état.", error: "Impossible de charger les abonnements." },
  en: { title: "Company subscriptions", intro: "Choose the company whose billing you manage.", choose: "Company", empty: "No active company to manage.", login: "Sign in to manage subscriptions.", load: "Loading…", status: "Billing status", none: "No active subscription", seats: "Active employees / paid seats", unlimited: "No per-employee limit", due: "Verified period end", review: "Reconciliation needed. Refresh the status or contact support.", over: "Verified seats do not cover the active roster. Subscription access is suspended until resolved.", portal: "Open billing portal", refresh: "Refresh subscription", updated: "Billing status refreshed.", standard: "Standard — per active employee", all: "All Inclusive — company plan", terms: "Stripe displays the price, taxes and billing interval before you confirm. Standard covers the entire active roster.", existing: "A subscription is already linked. Manage it in the portal; contact support for replacement.", support: "Contact support", back: "My dashboard", returned: "Back from Stripe: refresh the subscription to verify its status.", error: "Unable to load subscriptions." },
  ar: { title: "اشتراكات الشركات", intro: "اختر الشركة التي تدير فواتيرها.", choose: "الشركة", empty: "لا توجد شركة نشطة لإدارتها.", login: "سجّل الدخول لإدارة الاشتراكات.", load: "جارٍ التحميل…", status: "حالة الفوترة", none: "لا يوجد اشتراك نشط", seats: "الموظفون النشطون / المقاعد المدفوعة", unlimited: "دون حد لكل موظف", due: "نهاية الفترة المتحقق منها", review: "يلزم التحقق. حدّث الحالة أو تواصل مع الدعم.", over: "المقاعد المتحقق منها لا تغطي جميع الموظفين النشطين. الوصول المرتبط بالاشتراك معلق حتى التسوية.", portal: "فتح بوابة الفوترة", refresh: "تحديث الاشتراك", updated: "تم تحديث حالة الفوترة.", standard: "Standard — لكل موظف نشط", all: "All Inclusive — خطة الشركة", terms: "يعرض Stripe السعر والضرائب ودورية الفوترة قبل التأكيد. تغطي Standard جميع الموظفين النشطين.", existing: "يوجد اشتراك مرتبط بالفعل. أدره من البوابة؛ تواصل مع الدعم لاستبداله.", support: "التواصل مع الدعم", back: "لوحتي", returned: "بعد العودة من Stripe، حدّث الاشتراك للتحقق من حالته.", error: "تعذر تحميل الاشتراكات." },
};
export default function Subscriptions() {
  const { user, loading } = useAuth();
  const { lang } = useI18n();
  const c = copy[lang];
  const [selected, setSelected] = useState(() => Number(new URLSearchParams(window.location.search).get("companyId")) || 0);
  const orgs = trpc.billing.organizations.useQuery(undefined, { enabled: !!user });
  const companyId = orgs.data?.some(o => o.id === selected) ? selected : 0;
  const info = trpc.billing.subscription.useQuery({ companyId }, { enabled: !!companyId });
  const checkout = trpc.billing.checkout.useMutation({ onSuccess: r => { window.location.href = r.url; }, onError: e => { toast.error(e.message); info.refetch(); } });
  const portal = trpc.billing.portal.useMutation({ onSuccess: r => { window.location.href = r.url; }, onError: e => toast.error(e.message) });
  const refresh = trpc.billing.refresh.useMutation({ onSuccess: r => { info.refetch(); if (r.status === "requires_review") toast.warning(c.review); else toast.success(c.updated); }, onError: e => toast.error(e.message) });
  const resume = trpc.billing.resume.useMutation({ onSuccess: r => { window.location.href = r.url; }, onError: e => { toast.error(e.message); info.refetch(); } });
  const expire = trpc.billing.expire.useMutation({ onSuccess: r => { info.refetch(); if (r.status === "expired") toast.success(lang === "fr" ? "Session fermée. Vous pouvez choisir une formule." : lang === "ar" ? "أغلقت الجلسة. يمكنك اختيار خطة." : "Session closed. You can choose a plan."); else toast.info(c.updated); }, onError: e => { toast.error(e.message); info.refetch(); } });
  const busy = expire.isPending || checkout.isPending || portal.isPending || refresh.isPending || resume.isPending;
  const data = info.data;
  return <div className="min-h-screen bg-slate-50" dir={lang === "ar" ? "rtl" : "ltr"}><PublicNav /><main className="max-w-4xl mx-auto px-5 py-12 space-y-6">
    <Link href="/dashboard" className="text-sm underline">{c.back}</Link><header><h1 className="text-3xl font-serif">{c.title}</h1><p className="mt-2 text-slate-600">{c.intro}</p></header>
    {loading ? <p>{c.load}</p> : !user ? <Link href="/login" className="underline">{c.login}</Link> : <>
      {orgs.isLoading ? <p>{c.load}</p> : orgs.error ? <p role="alert">{c.error}</p> : !orgs.data?.length ? <p>{c.empty}</p> : <label className="block">{c.choose}<select className="block w-full rounded-lg border bg-white p-3 mt-2" value={companyId} disabled={busy} onChange={e => { setSelected(Number(e.target.value)); window.history.replaceState({}, "", `/abonnements?companyId=${e.target.value}`); }}><option value={0}>—</option>{orgs.data.map(o => <option value={o.id} key={o.id}>{o.name}</option>)}</select></label>}
      {companyId > 0 && (info.isLoading ? <p>{c.load}</p> : info.error ? <p role="alert">{info.error.message}</p> : data && <section className="rounded-2xl border bg-white p-6 space-y-5">
        {new URLSearchParams(window.location.search).has("subscription") && <p className="rounded-lg bg-blue-50 p-3">{c.returned}</p>}
        <h2 className="text-xl font-semibold">{orgs.data?.find(o => o.id === companyId)?.name}</h2>
        <p>{c.status} : <strong>{data.subscriptionStatus ?? c.none}</strong></p>
        <p>{c.seats} : {data.employeeCount} / {data.subscriptionType === "all_inclusive" ? c.unlimited : data.subscriptionQuantity ?? "—"}</p>
        {data.subscriptionExpiresAt && <p>{c.due} : {new Date(data.subscriptionExpiresAt).toLocaleDateString(lang)}</p>}
        {data.subscriptionType === "standard" && !data.capacityAvailable && <p role="alert" className="rounded-lg bg-amber-50 p-3 text-amber-900">{c.over}</p>}
        {data.subscriptionStatus === "requires_review" && <p role="alert">{c.review}</p>}
        <div className="flex flex-wrap gap-3"><Button disabled={busy} variant="outline" onClick={() => refresh.mutate({ companyId })}>{c.refresh}</Button>{data.hasStripeCustomer && <Button disabled={busy} onClick={() => portal.mutate({ companyId, origin: window.location.origin })}>{c.portal}</Button>}</div>
        {data.pendingCheckout && !data.hasStripeSubscription && <div className="rounded-xl bg-blue-50 p-4 space-y-3"><p>{lang === "fr" ? "Souscription en cours" : lang === "ar" ? "اشتراك قيد المعالجة" : "Subscription in progress"} : {data.pendingCheckout.plan} · {data.pendingCheckout.quantity}</p><Button disabled={busy} onClick={() => resume.mutate({ companyId, attemptId: data.pendingCheckout!.id })}>{lang === "fr" ? "Reprendre ou vérifier le paiement" : lang === "ar" ? "استئناف الدفع أو التحقق منه" : "Resume or verify payment"}</Button>{data.pendingCheckout.canExpire && <Button className="ms-2" variant="outline" disabled={busy} onClick={() => { if (window.confirm(lang === "fr" ? "Fermer cette session de paiement ? Son lien ne sera plus utilisable. Un paiement déjà terminé sera vérifié ; aucun remboursement ni résiliation d’abonnement ne sera demandé." : lang === "ar" ? "إغلاق جلسة الدفع؟ سيتوقف رابطها. سيتم التحقق من أي دفع مكتمل دون طلب استرداد أو إلغاء الاشتراك." : "Close this checkout session? Its link will stop working. A completed payment will be verified; this does not request a refund or cancel a subscription.")) expire.mutate({ companyId, attemptId: data.pendingCheckout!.id }); }}>{lang === "fr" ? "Fermer la session" : lang === "ar" ? "إغلاق الجلسة" : "Close session"}</Button>}</div>}
        {data.hasStripeSubscription ? <p className="text-sm text-slate-600">{c.existing}</p> : !data.pendingCheckout && <div className="border-t pt-5 space-y-4"><p className="text-sm text-slate-600">{c.terms}</p><div className="flex flex-wrap gap-3">{(["standard", "all_inclusive"] as const).map(plan => <Button key={plan} disabled={busy} onClick={() => checkout.mutate({ companyId, plan, origin: window.location.origin })}>{plan === "standard" ? c.standard : c.all}</Button>)}</div></div>}
        <Link href="/support" className="inline-block text-sm underline">{c.support}</Link>
      </section>)}
    </>}
  </main></div>;
}
