import { selectLearningEnrollment } from "../shared/learningEnrollment";
import { requestPedagogicalReview, decidePedagogicalReview } from "./pedagogicalReview";
import { archiveContent } from "./contentArchive";
import { beforeAll, describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { eq, sql } from "drizzle-orm";
import { getDb, createCourseWithSlides, getPublicTrainings, getTrainingBySlug, addToCart, updateTraining, createTraining, startExamSession, submitQuizAttempt, getTrainingModules, getQuizQuestions } from "./db";
import { users, companies, affiliations, trainings, slides, trainingModules, quizQuestions, enrollments, contentEvents, trainingVersions, learningObjectives } from "../drizzle/schema";
import { authorWorkspaces, courseOwnership, listAuthorCourses, requireAuthorCourse, requireAuthorSlides } from "./makerAccess";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";

const url = process.env.RAERO_TEST_DATABASE_URL;
describe.skipIf(!url)("studio ownership · PostgreSQL", () => {
  beforeAll(() => { process.env.DATABASE_URL = url!; });
  async function fixture() {
    const db = (await getDb())!;
    const [owner, stranger, admin] = await db.insert(users).values(["instructor", "company_manager", "admin"].map(role => ({ openId: randomUUID(), role: role as "instructor" | "company_manager" | "admin" }))).returning();
    const [company] = await db.insert(companies).values({ name: "Studio test" }).returning();
    await db.insert(affiliations).values({ personId: stranger.id, orgId: company.id, role: "MANAGER" });
    const personal = (await createCourseWithSlides({ title: "Personal", slug: randomUUID(), slides: [{ title: "Private draft" }], ...await courseOwnership(owner) }))!;
    const corporate = (await createCourseWithSlides({ title: "Corporate", slug: randomUUID(), slides: [{ title: "Company draft" }], ...await courseOwnership(stranger) }))!;
    const caller = (user: typeof owner) => appRouter.createCaller({ user, affiliations: [], req: { headers: {} }, res: {} } as unknown as TrpcContext);
    const approve = async (trainingId: number) => { const review = await requestPedagogicalReview(stranger, trainingId); await decidePedagogicalReview(admin, review.id, "approved", "Fixture content inspected"); };
    return { db, owner, stranger, admin, company, personal, corporate, caller, approve };
  }
  it("restricts course lists and every slide mutation to the author space", async () => {
    const { db, owner, stranger, admin, personal, corporate, caller } = await fixture();
    expect((await listAuthorCourses(owner)).map(c => c.id)).toContain(personal.trainingId);
    expect((await listAuthorCourses(owner)).map(c => c.id)).not.toContain(corporate.trainingId);
    await expect(requireAuthorCourse(stranger, personal.trainingId)).rejects.toMatchObject({ code: "FORBIDDEN" });
    expect(await requireAuthorCourse(admin, personal.trainingId)).toBeTruthy();
    const [slide] = await db.select().from(slides).where(eq(slides.trainingId, personal.trainingId));
    await expect(requireAuthorSlides(stranger, [slide.id])).rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller(stranger).maker.slides({ trainingId: personal.trainingId })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller(stranger).maker.updateSlide({ id: slide.id, title: "intrusion" })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller(stranger).maker.deleteSlide({ id: slide.id })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller(stranger).maker.reorderSlides({ orderedIds: [slide.id] })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller(stranger).maker.publish({ id: personal.trainingId, isPublished: true })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller(owner).maker.updateSlide({ id: slide.id, trainingId: corporate.trainingId })).rejects.toMatchObject({ code: "BAD_REQUEST" });
    await expect(caller(owner).maker.updateSlide({ id: slide.id, idOverride: 1 })).rejects.toMatchObject({ code: "BAD_REQUEST" });
    await caller(owner).maker.updateSlide({ id: slide.id, title: "Own edit" });
    expect((await db.select().from(slides).where(eq(slides.id, slide.id)))[0].title).toBe("Own edit");
  });
  it("revokes access with affiliation or company suspension, including creator access", async () => {
    const { db, stranger, company, corporate } = await fixture();
    await requireAuthorCourse(stranger, corporate.trainingId);
    await db.update(companies).set({ status: "SUSPENDED" }).where(eq(companies.id, company.id));
    await expect(requireAuthorCourse(stranger, corporate.trainingId)).rejects.toMatchObject({ code: "FORBIDDEN" });
    await db.update(companies).set({ status: "ACTIVE" }).where(eq(companies.id, company.id));
    await db.update(affiliations).set({ status: "INACTIVE" }).where(eq(affiliations.personId, stranger.id));
    await expect(requireAuthorCourse(stranger, corporate.trainingId)).rejects.toMatchObject({ code: "FORBIDDEN" });
    expect(await listAuthorCourses(stranger)).toHaveLength(0);
    await expect(courseOwnership(stranger)).rejects.toMatchObject({ code: "PRECONDITION_FAILED" });
  });
  it("keeps corporate courses out of public lookup and purchases even when published", async () => {
    const { db, owner, corporate, personal } = await fixture();
    const [course] = await db.update(trainings).set({ isPublished: true }).where(eq(trainings.id, corporate.trainingId)).returning();
    expect(await getTrainingBySlug(course.slug)).toBeNull();
    expect((await getPublicTrainings({})).map(c => c.id)).not.toContain(course.id);
    await expect(addToCart(owner.id, course.id)).rejects.toMatchObject({ code: "NOT_FOUND" });
    const [draft] = await db.select().from(trainings).where(eq(trainings.id, personal.trainingId));
    expect(await getTrainingBySlug(draft.slug)).toBeNull();
  });
  it("authors chapter content through the scoped API and rejects premature publication", async () => {
    const { db, stranger, owner, corporate, caller, approve } = await fixture();
    const api = caller(stranger);
    await expect(api.maker.publish({ id: corporate.trainingId, isPublished: true })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" });
    await expect(updateTraining(corporate.trainingId, { isPublished: true })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" });
    await expect(createTraining({ title: "Premature", slug: randomUUID(), isPublished: true })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" });
    await expect(caller(owner).maker.content.modules.create({ trainingId: corporate.trainingId, title: "Intrusion" })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await api.maker.content.modules.create({ trainingId: corporate.trainingId, title: "Chapter", content: "Learning material" });
    const [chapter] = await db.select().from(trainingModules).where(eq(trainingModules.trainingId, corporate.trainingId));
    await expect(caller(owner).maker.content.modules.update({ id: chapter.id, title: "Intrusion" })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await api.maker.content.modules.update({ id: chapter.id, title: "Validated title" });
    for (const moduleId of [chapter.id, null]) await api.maker.content.questions.create({ trainingId: corporate.trainingId, moduleId, question: "Choose A", type: "qcu", options: ["A", "B"], correctAnswer: [0] });
    const [slide] = await db.select().from(slides).where(eq(slides.trainingId, corporate.trainingId));
    expect((await api.maker.readiness({ trainingId: corporate.trainingId })).issues.some(i => i.code === "orphan")).toBe(true);
    await api.maker.updateSlide({ id: slide.id, moduleId: chapter.id });
    expect((await api.maker.readiness({ trainingId: corporate.trainingId })).ready).toBe(true);
    await approve(corporate.trainingId);
    await api.maker.publish({ id: corporate.trainingId, isPublished: true });
    expect((await db.select().from(trainings).where(eq(trainings.id, corporate.trainingId)))[0].isPublished).toBe(true);
    await expect(updateTraining(corporate.trainingId, { passingScore: 200 })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" });
    await api.maker.publish({ id: corporate.trainingId, isPublished: false });
  });
  it("takes a company course without Part-66 objectives through authoring, independent review, assignment and all exams", async () => {
    const { db, stranger, owner, admin, company, corporate, caller } = await fixture();
    const api = caller(stranger);
    const trainingId = corporate.trainingId;
    const [learner] = await db.insert(users).values({ openId: randomUUID(), role: 'user', name: 'Integrated learner' }).returning();
    await db.insert(affiliations).values({ personId: learner.id, orgId: company.id, role: 'MEMBER' });
    expect(await api.maker.objectives({ trainingId })).toHaveLength(0);
    for (const title of ['Preparation', 'Inspection']) await api.maker.content.modules.create({ trainingId, title, content: `${title} lesson`, isRequired: true });
    const chapters = await api.maker.content.modules.list({ trainingId });
    const [firstSlide] = await api.maker.slides({ trainingId });
    await api.maker.updateSlide({ id: firstSlide.id, moduleId: chapters[0].id, body: 'Preparation slide' });
    await api.maker.createSlide({ trainingId, moduleId: chapters[1].id, title: 'Inspection slide', body: 'Inspection material' });
    for (const moduleId of [...chapters.map(chapter => chapter.id), null]) await api.maker.content.questions.create({ trainingId, moduleId, question: 'Choose the verified instruction', type: 'qcu', options: ['Verified', 'Unverified'], correctAnswer: [0] });
    expect((await api.maker.readiness({ trainingId })).ready).toBe(true);
    await expect(api.maker.assign({ trainingId, userIds: [learner.id] })).rejects.toMatchObject({ code: 'PRECONDITION_FAILED' });
    await expect(api.maker.publish({ id: trainingId, isPublished: true })).rejects.toMatchObject({ code: 'PRECONDITION_FAILED' });
    const review = await api.maker.reviews.request({ trainingId });
    await expect(api.maker.reviews.decide({ reviewId: review.id, decision: 'approved', note: 'Own content' })).rejects.toMatchObject({ code: 'FORBIDDEN' });
    await caller(admin).maker.reviews.decide({ reviewId: review.id, decision: 'approved', note: 'Chapters, slides and assessments independently reviewed.' });
    await api.maker.publish({ id: trainingId, isPublished: true });
    await expect(api.maker.assign({ trainingId, userIds: [learner.id, owner.id] })).rejects.toMatchObject({ code: 'FORBIDDEN' });
    expect(await db.select().from(enrollments).where(eq(enrollments.trainingId, trainingId))).toHaveLength(0);
    expect(await api.maker.assign({ trainingId, userIds: [learner.id] })).toEqual({ created: 1, existing: 0 });
    expect(await api.maker.assign({ trainingId, userIds: [learner.id] })).toEqual({ created: 0, existing: 1 });
    const learnerApi = caller(learner);
    const enrollment = (await learnerApi.dashboard.enrollments()).find(row => row.trainingId === trainingId)!;
    expect(enrollment.trainingVersionId).toBeTruthy();
    const input = { trainingId, enrollmentId: enrollment.id };
    expect(await learnerApi.learning.modules(input)).toHaveLength(2);
    expect(await learnerApi.learning.objectives(input)).toHaveLength(0);
    await expect(caller(owner).learning.slides(input)).rejects.toMatchObject({ code: 'FORBIDDEN' });
    await expect(learnerApi.learning.startExam(input)).rejects.toMatchObject({ code: 'PRECONDITION_FAILED' });
    for (const [index, chapter] of chapters.entries()) {
      const session = (await learnerApi.learning.startExam({ ...input, moduleId: chapter.id }))!;
      expect(session.questions).toHaveLength(1);
      expect(session.questions[0]).not.toHaveProperty('correctAnswer');
      expect(session.questions[0]).not.toHaveProperty('explanation');
      expect(await learnerApi.learning.submitQuiz({ ...input, sessionId: session.sessionId, answers: { [session.questions[0].id]: [0] } })).toMatchObject({ isPassed: true });
      if (index === 0) await expect(learnerApi.learning.startExam(input)).rejects.toMatchObject({ code: 'PRECONDITION_FAILED' });
    }
    const final = (await learnerApi.learning.startExam(input))!;
    expect(final.questions).toHaveLength(1);
    const submission = { ...input, sessionId: final.sessionId, answers: { [final.questions[0].id]: [0] } };
    expect(await learnerApi.learning.submitQuiz(submission)).toMatchObject({ isPassed: true });
    expect(await learnerApi.learning.submitQuiz(submission)).toMatchObject({ isPassed: true });
    expect((await learnerApi.learning.quizAttempts({ enrollmentId: enrollment.id }))).toHaveLength(1);
    expect((await learnerApi.dashboard.enrollments()).find(row => row.id === enrollment.id)).toMatchObject({ status: 'completed' });
  });

  it("identifies malformed answer keys, empty chapter content and foreign links", async () => {
    const { db, stranger, corporate, personal, caller } = await fixture();
    const api = caller(stranger);
    await api.maker.content.modules.create({ trainingId: corporate.trainingId, title: "Empty" });
    const [chapter] = await db.select().from(trainingModules).where(eq(trainingModules.trainingId, corporate.trainingId));
    await api.maker.content.questions.create({ trainingId: corporate.trainingId, moduleId: chapter.id, question: "Bad answer key", type: "qcu", options: ["A", "B"], correctAnswer: [7] });
    const [foreign] = await db.insert(trainingModules).values({ trainingId: personal.trainingId, title: "Foreign" }).returning();
    await expect(api.maker.content.questions.create({ trainingId: corporate.trainingId, moduleId: foreign.id, question: "Intrusion", type: "qcu" })).rejects.toMatchObject({ code: "BAD_REQUEST" });
    const [q] = await db.select().from(quizQuestions).where(eq(quizQuestions.trainingId, corporate.trainingId));
    await expect(api.maker.content.questions.update({ id: q.id, moduleId: foreign.id })).rejects.toMatchObject({ code: "BAD_REQUEST" });
    const report = await api.maker.readiness({ trainingId: corporate.trainingId });
    expect(report.ready).toBe(false);
    expect(report.issues.map(i => i.code)).toEqual(expect.arrayContaining(["content", "question", "finalQuiz"]));
    await expect(api.maker.content.modules.delete({ id: chapter.id })).rejects.toMatchObject({ code: "CONFLICT" });
    expect(await db.select().from(trainingModules).where(eq(trainingModules.id, chapter.id))).toHaveLength(1);
  });

  it("archives draft questions without deletion, preserving immutable evidence and ownership", async () => {
    const { db, stranger, owner, corporate, caller, approve } = await fixture();
    const [question] = await db.insert(quizQuestions).values({ trainingId: corporate.trainingId, question: "Archive me", options: ["A", "B"], correctAnswer: [0] }).returning();
    await expect(caller(owner).maker.content.questions.delete({ id: question.id })).rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(updateTraining(corporate.trainingId, { archivedAt: new Date() })).rejects.toMatchObject({ code: "BAD_REQUEST" });
    await caller(stranger).maker.content.questions.delete({ id: question.id });
    expect((await getQuizQuestions(corporate.trainingId)).map(q => q.id)).not.toContain(question.id);
    expect((await db.select().from(quizQuestions).where(eq(quizQuestions.id, question.id)))[0].archivedAt).toBeInstanceOf(Date);
    const [event] = await caller(stranger).maker.history({ trainingId: corporate.trainingId });
    expect(event).toMatchObject({ actorId: stranger.id, action: "archived", entityId: question.id });
    expect(event.beforeState?.question).toBe("Archive me");
    await archiveContent("question", question.id, stranger.id);
    expect(await caller(stranger).maker.history({ trainingId: corporate.trainingId })).toHaveLength(1);
    await expect(db.update(contentEvents).set({ action: "changed" }).where(eq(contentEvents.id, event.id))).rejects.toThrow();
    await expect(db.delete(contentEvents).where(eq(contentEvents.id, event.id))).rejects.toThrow();
    await expect(db.update(quizQuestions).set({ question: "Changed" }).where(eq(quizQuestions.id, question.id))).rejects.toThrow();
    await expect(db.delete(quizQuestions).where(eq(quizQuestions.id, question.id))).rejects.toThrow();
    await expect(caller(owner).maker.history({ trainingId: corporate.trainingId })).rejects.toMatchObject({ code: "FORBIDDEN" });
  });
  it("archives a whole course while preserving the enrolled learner's final exam", async () => {
    const { db, stranger, corporate, caller } = await fixture();
    const [enrollment] = await db.insert(enrollments).values({ trainingId: corporate.trainingId, userId: stranger.id }).returning();
    const [question] = await db.insert(quizQuestions).values({ trainingId: corporate.trainingId, question: "Final", options: ["A", "B"], correctAnswer: [0] }).returning();
    const params = { trainingId: corporate.trainingId, enrollmentId: enrollment.id, userId: stranger.id, attemptNumber: 1 };
    const session = (await startExamSession(params))!;
    await expect(archiveContent("question", question.id, stranger.id)).rejects.toMatchObject({ code: "CONFLICT" });
    await caller(stranger).maker.archive({ trainingId: corporate.trainingId });
    expect((await listAuthorCourses(stranger)).map(c => c.id)).not.toContain(corporate.trainingId);
    expect(await submitQuizAttempt({ ...params, sessionId: session.sessionId, answers: { [question.id]: [0] } })).toMatchObject({ isPassed: true });
    expect(await db.select().from(enrollments).where(eq(enrollments.id, enrollment.id))).toHaveLength(1);
    await expect(db.insert(enrollments).values({ trainingId: corporate.trainingId, userId: stranger.id })).rejects.toThrow();
    await expect(db.delete(trainings).where(eq(trainings.id, corporate.trainingId))).rejects.toThrow();
    await expect(db.update(trainings).set({ title: "Changed" }).where(eq(trainings.id, corporate.trainingId))).rejects.toThrow();
    expect(await caller(stranger).maker.history({ trainingId: corporate.trainingId })).toHaveLength(1);
  });
  it("archives a chapter only after its linked active content has been handled", async () => {
    const { db, stranger, corporate, caller } = await fixture();
    const [chapter] = await db.insert(trainingModules).values({ trainingId: corporate.trainingId, title: "Chapter" }).returning();
    const [question] = await db.insert(quizQuestions).values({ trainingId: corporate.trainingId, moduleId: chapter.id, question: "Linked", options: ["A", "B"], correctAnswer: [0] }).returning();
    await expect(caller(stranger).maker.content.modules.delete({ id: chapter.id })).rejects.toMatchObject({ code: "CONFLICT" });
    await caller(stranger).maker.content.questions.delete({ id: question.id });
    await caller(stranger).maker.content.modules.delete({ id: chapter.id });
    expect(await getTrainingModules(corporate.trainingId)).toHaveLength(0);
    await expect(db.insert(quizQuestions).values({ trainingId: corporate.trainingId, moduleId: chapter.id, question: "Late link" })).rejects.toThrow();
    expect((await db.select().from(quizQuestions).where(eq(quizQuestions.id, question.id)))[0].moduleId).toBe(chapter.id);
  });

  it("pins published curriculum across author edits, new chapters, retries and later publications", async () => {
    const { db, stranger, owner, corporate, caller, approve } = await fixture();
    const api = caller(stranger), trainingId = corporate.trainingId;
    const [chapter] = await db.insert(trainingModules).values({ trainingId, title: "Original chapter", content: "Original lesson" }).returning();
    const [chapterQuestion, finalQuestion] = await db.insert(quizQuestions).values([
      { trainingId, moduleId: chapter.id, question: "Original chapter question", options: ["A", "B"], correctAnswer: [0] },
      { trainingId, question: "Original final", options: ["A", "B"], correctAnswer: [0] },
    ]).returning();
    const [objective] = await db.insert(learningObjectives).values({ trainingId, title: "Both assessments" }).returning();
    await db.update(quizQuestions).set({ objectiveId: objective.id }).where(eq(quizQuestions.trainingId, trainingId));
    await db.update(slides).set({ moduleId: chapter.id, body: "Original slide" }).where(eq(slides.trainingId, trainingId));
    await updateTraining(trainingId, { language: "ar" }, stranger.id);
    await approve(trainingId);
    await api.maker.publish({ id: trainingId, isPublished: true });
    const [first] = await db.insert(enrollments).values({ trainingId, userId: stranger.id }).returning();
    expect(first.trainingVersionId).toBeTypeOf("number");
    await db.update(trainingModules).set({ title: "Changed chapter", content: "Changed lesson", quizMaxAttempts: 1 }).where(eq(trainingModules.id, chapter.id));
    await db.update(quizQuestions).set({ question: "Changed final", correctAnswer: [1] }).where(eq(quizQuestions.id, finalQuestion.id));
    await db.update(slides).set({ body: "Changed slide" }).where(eq(slides.trainingId, trainingId));
    const [added] = await db.insert(trainingModules).values({ trainingId, title: "New required chapter", content: "New lesson", sortOrder: 1 }).returning();
    await db.insert(quizQuestions).values({ trainingId, moduleId: added.id, question: "New quiz", options: ["A", "B"], correctAnswer: [0] });
    await updateTraining(trainingId, { maxAttempts: 1, language: "en" }, stranger.id);
    await approve(trainingId);
    await updateTraining(trainingId, { isPublished: true }, stranger.id);
    const [second] = await db.insert(enrollments).values({ trainingId, userId: owner.id }).returning();
    expect((await api.dashboard.enrollments()).find(e => e.id === first.id)?.training?.language).toBe("ar");
    expect((await caller(owner).dashboard.enrollments()).find(e => e.id === second.id)?.training?.language).toBe("en");
    expect(second.trainingVersionId).not.toBe(first.trainingVersionId);
    const [renewed] = await db.insert(enrollments).values({ trainingId, userId: stranger.id }).returning();
    expect(renewed.trainingVersionId).toBe(second.trainingVersionId);
    const ownEnrollments = await api.dashboard.enrollments();
    const slug = ownEnrollments.find(e => e.id === first.id)!.training!.slug;
    const selectedOld = selectLearningEnrollment(ownEnrollments, slug, `enrollment=${first.id}`)!;
    const selectedNew = selectLearningEnrollment(ownEnrollments, slug, `enrollment=${renewed.id}`)!;
    expect(selectedOld.training?.language).toBe('ar');
    expect(selectedNew.training?.language).toBe('en');
    expect(selectLearningEnrollment(ownEnrollments, slug, '')).toBeUndefined();
    const oldDetail = await api.dashboard.enrollment({ id: first.id });
    const renewedDetail = await api.dashboard.enrollment({ id: renewed.id });
    expect(oldDetail?.training?.language).toBe('ar');
    expect(oldDetail?.modules.map(m => m.content)).toEqual(['Original lesson']);
    expect(renewedDetail?.training?.language).toBe('en');
    expect(renewedDetail?.modules.map(m => m.content)).toEqual(['Changed lesson', 'New lesson']);
    expect(await caller(owner).dashboard.enrollment({ id: first.id })).toBeNull();
    expect(await api.dashboard.enrollment({ id: second.id })).toBeNull();
    expect((await api.learning.modules({ trainingId, enrollmentId: selectedNew.id })).map(m => m.title)).toEqual(['Changed chapter', 'New required chapter']);
    expect((await api.learning.slides({ trainingId, enrollmentId: selectedNew.id }))[0].body).toBe('Changed slide');
    const renewedQuestions = await api.learning.quizQuestions({ trainingId, enrollmentId: selectedNew.id });
    expect(renewedQuestions[0].question).toBe('Changed final');
    expect(renewedQuestions[0]).not.toHaveProperty('correctAnswer');
    expect((await api.learning.modules({ trainingId, enrollmentId: first.id })).map(m => m.title)).toEqual(["Original chapter"]);
    expect((await api.learning.slides({ trainingId, enrollmentId: first.id }))[0].body).toBe("Original slide");
    expect((await caller(owner).learning.modules({ trainingId, enrollmentId: second.id }))).toHaveLength(2);
    await expect(caller(owner).learning.modules({ trainingId, enrollmentId: first.id })).rejects.toMatchObject({ code: "FORBIDDEN" });
    const publicQuestions = await api.learning.quizQuestions({ trainingId, enrollmentId: first.id });
    expect(publicQuestions[0].question).toBe("Original final");
    expect(publicQuestions[0]).not.toHaveProperty("correctAnswer");
    const params = { trainingId, enrollmentId: first.id, userId: stranger.id, attemptNumber: 1 };
    const chapterSession = (await startExamSession({ ...params, moduleId: chapter.id }))!;
    await submitQuizAttempt({ ...params, sessionId: chapterSession.sessionId, answers: { [chapterQuestion.id]: [0] } });
    const final = (await startExamSession(params))!;
    expect(final.questions.map(q => q.question)).toEqual(["Original final"]);
    expect(await submitQuizAttempt({ ...params, sessionId: final.sessionId, answers: { [finalQuestion.id]: [1] } })).toMatchObject({ isPassed: false });
    const retry = (await startExamSession(params))!;
    expect(retry.attemptNumber).toBe(2);
    expect(await submitQuizAttempt({ ...params, sessionId: retry.sessionId, answers: { [finalQuestion.id]: [0] } })).toMatchObject({ isPassed: true });
    await expect(startExamSession({ ...params, userId: owner.id, enrollmentId: second.id })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" });
    expect((await api.learning.objectiveProgress({ enrollmentId: first.id })).find(o => o.id === objective.id)?.isCompleted).toBe(true);
    // Completing the old enrollment must not credit the same account's renewed enrollment.
    const completedDetail = await api.dashboard.enrollment({ id: first.id });
    expect(completedDetail?.progress.find(p => p.moduleId === chapter.id)?.isCompleted).toBe(true);
    expect(completedDetail?.progress.every(p => p.enrollmentId === first.id)).toBe(true);
    expect((await api.dashboard.enrollment({ id: renewed.id }))?.progress).toEqual([]);
    expect(await api.learning.quizAttempts({ enrollmentId: renewed.id })).toEqual([]);
    expect((await api.learning.objectiveProgress({ enrollmentId: renewed.id })).find(o => o.id === objective.id)?.isCompleted).toBe(false);
    await expect(startExamSession({ ...params, enrollmentId: renewed.id })).rejects.toMatchObject({ code: 'PRECONDITION_FAILED' });
    const renewedChapter = (await startExamSession({ ...params, enrollmentId: renewed.id, moduleId: chapter.id }))!;
    expect(renewedChapter.attemptNumber).toBe(1);
    await expect(submitQuizAttempt({ ...params, enrollmentId: first.id, moduleId: chapter.id, sessionId: renewedChapter.sessionId, answers: { [chapterQuestion.id]: [0] } })).rejects.toThrow();
    expect(await submitQuizAttempt({ ...params, enrollmentId: renewed.id, moduleId: chapter.id, sessionId: renewedChapter.sessionId, answers: { [chapterQuestion.id]: [0] } })).toMatchObject({ isPassed: true });
    await expect(startExamSession({ ...params, enrollmentId: renewed.id })).rejects.toMatchObject({ code: 'PRECONDITION_FAILED' });
    await api.maker.publish({ id: trainingId, isPublished: false });
    await archiveContent("question", chapterQuestion.id, stranger.id);
    const retainedDetail = await api.dashboard.enrollment({ id: first.id });
    expect(retainedDetail?.training?.language).toBe('ar');
    expect(retainedDetail?.modules.map(m => m.content)).toEqual(['Original lesson']);
    const retained = (await startExamSession({ ...params, userId: owner.id, enrollmentId: second.id, moduleId: chapter.id }))!;
    expect(retained.questions[0].id).toBe(chapterQuestion.id);
    expect((await api.maker.versions({ trainingId })).map(v => v.version)).toEqual([2, 1]);
    await expect(db.update(enrollments).set({ trainingVersionId: second.trainingVersionId }).where(eq(enrollments.id, first.id))).rejects.toThrow();
    await expect(db.update(trainingVersions).set({ version: 99 }).where(eq(trainingVersions.id, first.trainingVersionId!))).rejects.toThrow();
    await expect(db.delete(trainingVersions).where(eq(trainingVersions.id, first.trainingVersionId!))).rejects.toThrow();
  });

  it("offers active workspaces to affiliation managers without a legacy global role", async () => {
    const { db, admin } = await fixture();
    const [manager] = await db.insert(users).values({ openId: randomUUID(), role: "user" }).returning();
    const organizations = await db.insert(companies).values([{ name: "Workspace A" }, { name: "Workspace B" }, { name: "Workspace suspended", status: "SUSPENDED" }]).returning();
    const memberships = await db.insert(affiliations).values(organizations.map(o => ({ personId: manager.id, orgId: o.id, role: "MANAGER" as const }))).returning();
    const caller = appRouter.createCaller({ user: manager, affiliations: memberships, req: { headers: {} }, res: {} } as unknown as TrpcContext);
    expect((await caller.maker.workspaces()).map(w => w.orgId).sort()).toEqual(organizations.slice(0, 2).map(o => o.id).sort());
    await expect(courseOwnership(manager)).rejects.toMatchObject({ code: "PRECONDITION_FAILED" });
    const created = await caller.maker.createCourse({ title: "Internal B", slug: randomUUID(), orgId: organizations[1].id, slides: [] });
    expect((await db.select().from(trainings).where(eq(trainings.id, created!.trainingId)))[0].ownerOrgId).toBe(organizations[1].id);
    await expect(courseOwnership(admin, organizations[2].id)).rejects.toMatchObject({ code: "FORBIDDEN" });
    await db.update(affiliations).set({ status: "INACTIVE" }).where(eq(affiliations.id, memberships[1].id));
    expect((await authorWorkspaces(manager)).map(w => w.orgId)).toEqual([organizations[0].id]);
    await expect(courseOwnership(manager, organizations[1].id)).rejects.toMatchObject({ code: "FORBIDDEN" });
  });

});
