import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Button} from '@/components/ui/button';
export default function AdminCertificates(){
 const {lang}=useI18n();
 const l=lang==='fr'?{title:'Certificats',number:'Numéro du certificat',search:'Rechercher',reason:'Motif de révocation (10 caractères minimum)',confirm:'Je confirme la révocation définitive de ce certificat.',revoke:'Révoquer',missing:'Aucun certificat trouvé.',valid:'Valide',expired:'Expiré',revoked:'Révoqué',legacy:'Révocation antérieure sans historique disponible.'}:lang==='ar'?{title:'الشهادات',number:'رقم الشهادة',search:'بحث',reason:'سبب الإلغاء (10 أحرف على الأقل)',confirm:'أؤكد الإلغاء النهائي لهذه الشهادة.',revoke:'إلغاء الشهادة',missing:'لم يتم العثور على شهادة.',valid:'صالحة',expired:'منتهية الصلاحية',revoked:'ملغاة',legacy:'إلغاء سابق دون سجل متاح.'}:{title:'Certificates',number:'Certificate number',search:'Search',reason:'Revocation reason (at least 10 characters)',confirm:'I confirm permanent revocation of this certificate.',revoke:'Revoke',missing:'No certificate found.',valid:'Valid',expired:'Expired',revoked:'Revoked',legacy:'Previously revoked; no history available.'};
 const [number,setNumber]=useState(''),[search,setSearch]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const query=trpc.admin.certificate.useQuery({number:search},{enabled:!!search});
 const mutation=trpc.admin.revokeCertificate.useMutation({onSuccess:()=>{setReason('');setConfirmed(false);void query.refetch();}});
 const cert=query.data;
 return <section className="rounded-xl border bg-card p-6 space-y-4" dir={lang==='ar'?'rtl':'ltr'}><h2 className="text-xl font-semibold">{l.title}</h2><form className="flex items-end gap-3" onSubmit={e=>{e.preventDefault();setSearch(number.trim());setReason('');setConfirmed(false);mutation.reset();}}><label className="flex-1">{l.number}<input className="block border rounded p-2 w-full" maxLength={64} value={number} onChange={e=>setNumber(e.target.value)} disabled={mutation.isPending}/></label><Button disabled={!number.trim()||mutation.isPending}>{l.search}</Button></form>{query.isFetching&&<p role="status">…</p>}{(query.error||mutation.error)&&<p role="alert">{(query.error||mutation.error)?.message}</p>}{search&&query.isSuccess&&!cert&&<p>{l.missing}</p>}{cert&&!query.isFetching&&<div className="space-y-3"><p className="font-mono">{cert.certificateNumber}</p><p>{cert.holder} · {cert.title}</p><p className="font-semibold">{l[cert.status]}</p>{cert.revocation?<div className="border rounded p-3"><p>{cert.revocation.reason}</p><p className="text-sm">{cert.revocation.actorName} · {new Date(cert.revocation.createdAt).toLocaleString(lang)}</p></div>:cert.status==='revoked'?<p>{l.legacy}</p>:<><label className="block">{l.reason}<textarea className="block border rounded p-2 w-full" maxLength={2000} value={reason} disabled={mutation.isPending} onChange={e=>setReason(e.target.value)}/></label><label className="flex gap-2 items-start"><input type="checkbox" checked={confirmed} disabled={mutation.isPending} onChange={e=>setConfirmed(e.target.checked)}/>{l.confirm}</label><Button variant="destructive" disabled={!confirmed||reason.trim().length<10||mutation.isPending} onClick={()=>mutation.mutate({certificateNumber:cert.certificateNumber,reason})}>{l.revoke}</Button></>}</div>}</section>;
}
