import LiveInstructorsDialog from "./LiveInstructorsDialog";
import WebinarHistoryDialog from "./WebinarHistoryDialog";
import WebinarMetadataDialog from "./WebinarMetadataDialog";
import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {toast} from 'sonner';
type Mode={kind:'create'}|{kind:'schedule'|'status';id:number;scheduledAt:Date;durationMinutes:number|null};
export default function AdminWebinars(){
 const {lang}=useI18n(),utils=trpc.useUtils();
 const text=lang==='fr'?{title:'Webinaires',create:'Créer un webinaire',schedule:'Horaires',status:'Statut',name:'Titre',date:'Début (heure locale)',duration:'Durée en minutes (1 à 1440)',capacity:'Places',training:'Formation de rattachement',none:'Sans formation — catalogue public',reason:'Motif',save:'Enregistrer',cancel:'Fermer',notice:'La durée est obligatoire pour l’accès vidéo. Une formation interne masque le webinaire du catalogue public. Les droits de modération restent contrôlés par le serveur.',scheduled:'Planifié',live:'En direct',completed:'Terminé',cancelled:'Annulé',loading:'Chargement…',retry:'Réessayer'}:lang==='ar'?{title:'الندوات',create:'إنشاء ندوة',schedule:'المواعيد',status:'الحالة',name:'العنوان',date:'البداية (التوقيت المحلي)',duration:'المدة بالدقائق (1 إلى 1440)',capacity:'المقاعد',training:'الدورة المرتبطة',none:'بدون دورة — الكتالوج العام',reason:'السبب',save:'حفظ',cancel:'إغلاق',notice:'المدة مطلوبة للفيديو. الدورة الداخلية تخفي الندوة من الكتالوج العام. يتحقق الخادم من صلاحيات الإشراف.',scheduled:'مجدول',live:'مباشر',completed:'مكتمل',cancelled:'ملغى',loading:'جار التحميل…',retry:'إعادة المحاولة'}:{title:'Webinars',create:'Create webinar',schedule:'Schedule',status:'Status',name:'Title',date:'Start (local time)',duration:'Duration in minutes (1 to 1440)',capacity:'Seats',training:'Linked course',none:'No course — public catalogue',reason:'Reason',save:'Save',cancel:'Close',notice:'A duration is required for video access. Internal courses hide the webinar from the public catalogue. Moderator permissions remain enforced by the server.',scheduled:'Scheduled',live:'Live',completed:'Completed',cancelled:'Cancelled',loading:'Loading…',retry:'Retry'};
 const query=trpc.admin.webinars.list.useQuery(),courses=trpc.admin.trainings.list.useQuery();
 const [instructorRoom,setInstructorRoom]=useState<number|null>(null);
 const [historyId,setHistoryId]=useState<number|null>(null);
 const [editing,setEditing]=useState<NonNullable<typeof query.data>[number]|null>(null);
 const [mode,setMode]=useState<Mode|null>(null),[title,setTitle]=useState(''),[start,setStart]=useState(''),[duration,setDuration]=useState('60'),[capacity,setCapacity]=useState('50'),[trainingId,setTrainingId]=useState(''),[reason,setReason]=useState(''),[status,setStatus]=useState<'live'|'completed'|'cancelled'>('live');
 const saved=()=>{setMode(null);utils.admin.webinars.list.invalidate();utils.admin.webinars.history.invalidate();utils.webinars.list.invalidate();utils.public.webinars.invalidate();utils.live.access.invalidate();};
 const failed=(e:{message:string})=>toast.error(e.message);
 const create=trpc.admin.webinars.create.useMutation({onSuccess:saved,onError:failed}),schedule=trpc.admin.webinars.schedule.useMutation({onSuccess:saved,onError:failed}),change=trpc.admin.webinars.setStatus.useMutation({onSuccess:saved,onError:failed});
 const pending=create.isPending||schedule.isPending||change.isPending;
 function open(next:Mode){setMode(next);setReason('');setStatus('live');if(next.kind==='create'){setTitle('');setStart('');setDuration('60');setCapacity('50');setTrainingId('');}else{const d=new Date(next.scheduledAt);setStart(new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16));setDuration(String(next.durationMinutes??''));}}
 return <section className="mt-10 space-y-4"><div className="flex justify-between"><h2 className="font-semibold">{text.title}</h2><Button onClick={()=>open({kind:'create'})}>{text.create}</Button></div>
 {query.isLoading?<p>{text.loading}</p>:query.error?<div role="alert">{query.error.message}<Button variant="outline" onClick={()=>query.refetch()}>{text.retry}</Button></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{[text.name,text.date,text.duration,text.capacity,text.status,''].map((label,i)=><th key={i} className="text-start p-2">{label}</th>)}</tr></thead><tbody>{query.data?.map(w=><tr key={w.id} className="border-t"><td className="p-2">{w.title}</td><td className="p-2">{new Date(w.scheduledAt).toLocaleString(lang)}</td><td className="p-2">{w.durationMinutes??'—'}</td><td className="p-2">{w.registeredCount}/{w.maxParticipants??'∞'}</td><td className="p-2">{w.status?text[w.status]:'—'}</td><td className="p-2"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setInstructorRoom(w.id)}>{lang==='fr'?'Instructeurs':lang==='ar'?'المدربون':'Instructors'}</Button><Button size="sm" variant="outline" onClick={()=>setHistoryId(w.id)}>{lang==='fr'?'Historique':lang==='ar'?'السجل':'History'}</Button><Button size="sm" variant="outline" disabled={w.status==='completed'||w.status==='cancelled'} onClick={()=>setEditing(w)}>{lang==='fr'?'Modifier':lang==='ar'?'تعديل':'Edit'}</Button><Button size="sm" variant="outline" disabled={w.status==='completed'||w.status==='cancelled'} onClick={()=>open({kind:'schedule',...w})}>{text.schedule}</Button><Button size="sm" variant="outline" disabled={w.status==='completed'||w.status==='cancelled'} onClick={()=>open({kind:'status',...w})}>{text.status}</Button></div></td></tr>)}</tbody></table></div>}
 {instructorRoom!=null&&<LiveInstructorsDialog key={instructorRoom} roomType="webinar" roomId={instructorRoom} onClose={()=>setInstructorRoom(null)}/>}
 {historyId!=null&&<WebinarHistoryDialog key={historyId} id={historyId} onClose={()=>setHistoryId(null)}/>}
 {editing&&<WebinarMetadataDialog webinar={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);saved();}}/>}
 {mode&&<Dialog open onOpenChange={value=>{if(!value&&!pending)setMode(null);}}><DialogContent><DialogHeader><DialogTitle>{mode.kind==='create'?text.create:mode.kind==='schedule'?text.schedule:text.status}</DialogTitle></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();if(mode.kind==='status')change.mutate({id:mode.id,status,reason});else if(mode.kind==='schedule')schedule.mutate({id:mode.id,scheduledAt:new Date(start).toISOString(),durationMinutes:Number(duration),reason});else create.mutate({title,scheduledAt:new Date(start).toISOString(),durationMinutes:Number(duration),maxParticipants:Number(capacity),trainingId:trainingId?Number(trainingId):null});}}>
 <p className="text-sm text-muted-foreground">{text.notice}</p>
 {mode.kind==='create'&&<><label htmlFor="webinar-title">{text.name}</label><Input id="webinar-title" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={255} disabled={pending}/><label htmlFor="webinar-course">{text.training}</label><select id="webinar-course" className="w-full border rounded p-2" value={trainingId} onChange={e=>setTrainingId(e.target.value)} disabled={pending}><option value="">{text.none}</option>{courses.data?.filter(c=>!c.archivedAt).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><label htmlFor="webinar-capacity">{text.capacity}</label><Input id="webinar-capacity" type="number" min={1} max={10000} required value={capacity} onChange={e=>setCapacity(e.target.value)} disabled={pending}/></>}
 {mode.kind!=='status'&&<><label htmlFor="webinar-start">{text.date}</label><Input id="webinar-start" type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)} disabled={pending}/><label htmlFor="webinar-duration">{text.duration}</label><Input id="webinar-duration" type="number" min={1} max={1440} required value={duration} onChange={e=>setDuration(e.target.value)} disabled={pending}/></>}
 {mode.kind==='status'&&<><label htmlFor="webinar-status">{text.status}</label><select id="webinar-status" className="w-full border rounded p-2" value={status} onChange={e=>setStatus(e.target.value as typeof status)} disabled={pending}>{(['live','completed','cancelled'] as const).map(s=><option key={s} value={s}>{text[s]}</option>)}</select></>}
 {mode.kind!=='create'&&<><label htmlFor="webinar-reason">{text.reason}</label><Input id="webinar-reason" required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} disabled={pending}/></>}
 <div className="flex gap-2"><Button type="submit" disabled={pending}>{text.save}</Button><Button type="button" variant="outline" disabled={pending} onClick={()=>setMode(null)}>{text.cancel}</Button></div>
 </form></DialogContent></Dialog>}
 </section>;
}
