import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Button} from '@/components/ui/button';
import {requestId} from '@/lib/requestId';
export default function AiVideoGenerator({trainingId,onUse}:{trainingId:number;onUse:(url:string)=>void}){
 const {lang}=useI18n();const t=lang==='fr'?{title:'Vidéo IA',prompt:'Décrivez la scène pédagogique',generate:'Générer une vidéo',retry:'Retrouver la demande',refresh:'Vérifier la génération',use:'Utiliser cette vidéo',quota:'Demandes sur la dernière heure',disabled:'La génération vidéo Google n’est pas configurée.',note:'Clips courts générés par IA : vérifiez leur exactitude avant publication. Les 50 dernières demandes de cette formation sont affichées.',unknown:'Issue inconnue : aucune génération ne sera relancée automatiquement.',submitting:'Envoi en cours',running:'Génération en cours',ready:'Vidéo disponible',failed:'Aucune vidéo produite',empty:'Aucune demande pour cette formation.'}:lang==='ar'?{title:'فيديو بالذكاء الاصطناعي',prompt:'صف المشهد التعليمي',generate:'توليد فيديو',retry:'استرجاع الطلب',refresh:'التحقق من التوليد',use:'استخدام هذا الفيديو',quota:'طلبات الساعة الأخيرة',disabled:'توليد فيديو Google غير مهيأ.',note:'مقاطع قصيرة مولدة بالذكاء الاصطناعي: تحقق من دقتها قبل النشر. تظهر آخر 50 طلباً لهذه الدورة.',unknown:'النتيجة غير معروفة: لن يُعاد التوليد تلقائياً.',submitting:'جار الإرسال',running:'جار التوليد',ready:'الفيديو متاح',failed:'لم يتم إنتاج فيديو',empty:'لا توجد طلبات لهذه الدورة.'}:{title:'AI video',prompt:'Describe the teaching scene',generate:'Generate video',retry:'Recover request',refresh:'Check generation',use:'Use this video',quota:'Requests in the last hour',disabled:'Google video generation is not configured.',note:'Short AI-generated clips: check their accuracy before publishing. The latest 50 requests for this course are shown.',unknown:'Outcome unknown: generation will not restart automatically.',submitting:'Submitting',running:'Generating',ready:'Video available',failed:'No video produced',empty:'No requests for this course.'};
 const query=trpc.ai.videos.useQuery({trainingId},{refetchInterval:15000});const [prompt,setPrompt]=useState(''),[duration,setDuration]=useState<4|6|8>(8),[ratio,setRatio]=useState<'16:9'|'9:16'>('16:9');
 const [pending,setPending]=useState<{id:string;trainingId:number;prompt:string;durationSeconds:4|6|8;aspectRatio:'16:9'|'9:16'}|null>(null);
 const start=trpc.ai.startVideo.useMutation({onSuccess:()=>setPending(null),onSettled:()=>query.refetch()});const refresh=trpc.ai.refreshVideo.useMutation({onSettled:()=>query.refetch()});
 const run=()=>{const input=pending??{id:requestId(),trainingId,prompt,durationSeconds:duration,aspectRatio:ratio};setPending(input);start.mutate(input);};
 return <details className="border rounded p-2 mb-2 text-xs"><summary className="cursor-pointer font-medium">{t.title}</summary><div className="space-y-2 mt-2"><p>{t.note}</p>{query.error?<p role="alert">{query.error.message}</p>:query.data&&<><p>{t.quota}: {query.data.used}/{query.data.limit}</p>{!query.data.configured&&<p>{t.disabled}</p>}<fieldset disabled={start.isPending||pending!=null||!query.data.configured} className="space-y-2"><label className="block">{t.prompt}<textarea maxLength={5000} value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3} className="w-full border rounded p-2"/></label><div className="flex gap-2"><select aria-label={lang==='fr'?'Durée':lang==='ar'?'المدة':'Duration'} value={duration} onChange={e=>setDuration(Number(e.target.value) as 4|6|8)} className="border rounded p-1">{[4,6,8].map(n=><option key={n} value={n}>{n} s</option>)}</select><select aria-label={lang==='ar'?'نسبة العرض':'Aspect ratio'} value={ratio} onChange={e=>setRatio(e.target.value as '16:9'|'9:16')} className="border rounded p-1"><option>16:9</option><option>9:16</option></select></div></fieldset><Button size="sm" variant="outline" disabled={start.isPending||(!pending&&(!query.data.configured||prompt.trim().length<2))} onClick={run}>{pending?t.retry:t.generate}</Button>{!query.data.entries.length&&<p>{t.empty}</p>}<ul className="space-y-2">{query.data.entries.map(row=><li key={row.id} className="border rounded p-2 space-y-1"><p>{new Date(row.createdAt).toLocaleString(lang)} · {row.durationSeconds} s</p><p role="status">{row.status==='unknown'?t.unknown:row.status==='submitting'?t.submitting:row.status==='running'?t.running:row.status==='ready'?t.ready:t.failed}</p>{(row.status==='running'||row.status==='submitting')&&<Button size="sm" variant="outline" disabled={refresh.isPending} onClick={()=>refresh.mutate({id:row.id})}>{t.refresh}</Button>}{row.url&&<><video src={row.url} controls preload="none" className="w-full rounded"/><Button size="sm" variant="outline" onClick={()=>onUse(row.url!)}>{t.use}</Button></>}</li>)}</ul></>}{refresh.data && "retry" in refresh.data && refresh.data.retry && <p role="alert">{lang === "fr" ? "Vérification indisponible. Réessayez dans quelques instants ; aucune nouvelle génération ne sera lancée." : lang === "ar" ? "التحقق غير متاح. أعد المحاولة لاحقاً؛ لن يبدأ توليد جديد." : "Status check unavailable. Try again shortly; this will not start a new generation."}</p>}{(start.error||refresh.error)&&<p role="alert">{start.error?.message||refresh.error?.message}</p>}</div></details>;
}
