import {useState} from 'react';
import {Link} from 'wouter';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
function localDay(date:Date){return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10);}
export default function InstructorAgenda(){
 const {lang}=useI18n();
 const t=lang==='fr'?{title:'Mes classes à animer',from:'Du',to:'Au',apply:'Afficher',notice:'Vos affectations actives uniquement. Les droits et horaires sont revérifiés à l’ouverture de la salle. Dates dans votre fuseau local.',empty:'Aucune classe affectée sur cette période.',open:'Ouvrir la classe',session:'Session',webinar:'Webinaire',scheduled:'Planifiée',full:'Complète',live:'En direct',completed:'Terminée',cancelled:'Annulée',unknown:'Fin à préciser',previous:'Précédent',next:'Suivant',loading:'Chargement…',retry:'Réessayer',invalid:'Choisissez une période valide de 92 jours maximum.'}:lang==='ar'?{title:'الفصول الموكلة إليّ',from:'من',to:'إلى',apply:'عرض',notice:'التعيينات النشطة فقط. يتم التحقق من الحقوق والمواعيد عند فتح الغرفة. التواريخ بتوقيتك المحلي.',empty:'لا توجد فصول معينة في هذه الفترة.',open:'فتح الفصل',session:'جلسة',webinar:'ندوة',scheduled:'مجدول',full:'ممتلئ',live:'مباشر',completed:'مكتمل',cancelled:'ملغى',unknown:'يجب تحديد النهاية',previous:'السابق',next:'التالي',loading:'جار التحميل…',retry:'إعادة المحاولة',invalid:'اختر فترة صالحة لا تتجاوز 92 يوماً.'}:{title:'My teaching classes',from:'From',to:'To',apply:'Show',notice:'Your active assignments only. Permissions and times are checked again when you open a room. Dates use your local time zone.',empty:'No assigned classes in this period.',open:'Open class',session:'Session',webinar:'Webinar',scheduled:'Scheduled',full:'Full',live:'Live',completed:'Completed',cancelled:'Cancelled',unknown:'End needs scheduling',previous:'Previous',next:'Next',loading:'Loading…',retry:'Retry',invalid:'Choose a valid period of no more than 92 days.'};
 const [from,setFrom]=useState(()=>localDay(new Date())),[to,setTo]=useState(()=>localDay(new Date(Date.now()+30*86400000)));
 const bounds=(f:string,t:string)=>{const start=new Date(`${f}T00:00:00`),end=new Date(`${t}T00:00:00`);end.setDate(end.getDate()+1);return {from:start.toISOString(),to:end.toISOString()};};
 const [range,setRange]=useState(()=>bounds(from,to)),[error,setError]=useState(false),[cursors,setCursors]=useState<Array<{startsAt:string;assignmentId:number}|undefined>>([undefined]);
 const query=trpc.live.myClasses.useQuery({...range,after:cursors[cursors.length-1]},{refetchInterval:60000});
 return <section className="space-y-4"><h2 className="text-xl font-semibold">{t.title}</h2><p className="text-sm text-muted-foreground">{t.notice}</p><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();if(!from||!to||Date.parse(to)<Date.parse(from)||Date.parse(to)-Date.parse(from)>91*86400000){setError(true);return;}setError(false);setRange(bounds(from,to));setCursors([undefined]);}}><div><label htmlFor="agenda-from">{t.from}</label><Input id="agenda-from" type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label htmlFor="agenda-to">{t.to}</label><Input id="agenda-to" type="date" required value={to} onChange={e=>setTo(e.target.value)}/></div><Button type="submit">{t.apply}</Button></form>{error&&<p role="alert">{t.invalid}</p>}
 {query.isLoading?<p role="status">{t.loading}</p>:query.error?<div role="alert">{query.error.message}<Button variant="outline" onClick={()=>query.refetch()}>{t.retry}</Button></div>:<>{!query.data?.entries.length&&<p>{t.empty}</p>}<ul className="space-y-3">{query.data?.entries.map(row=><li key={row.assignmentId} className="border rounded-lg p-4 bg-card flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{row.title}</h3><p className="text-sm">{t[row.roomType]} · {row.status?t[row.status as 'scheduled']??row.status:'—'}</p><p className="text-sm text-muted-foreground">{new Date(row.startsAt).toLocaleString(lang)} → {row.endsAt?new Date(row.endsAt).toLocaleString(lang):t.unknown}</p></div>{row.status!=='cancelled'&&<Link href={`/live/${row.roomType}/${row.roomId}`}><Button variant="outline">{t.open}</Button></Link>}</li>)}</ul><div className="flex gap-2"><Button variant="outline" disabled={cursors.length<2||query.isFetching} onClick={()=>setCursors(v=>v.slice(0,-1))}>{t.previous}</Button><Button variant="outline" disabled={!query.data?.nextCursor||query.isFetching} onClick={()=>setCursors(v=>[...v,query.data!.nextCursor!])}>{t.next}</Button></div></>}
 </section>;
}
