import {useState} from 'react';
import type {InvoiceLanguage} from '../../../shared/invoiceLanguage';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {invoiceBuyerSchema} from '../../../shared/invoiceIdentity';
export default function InvoiceRequestDialog({orderId,initialName,onClose,onGenerated}:{orderId:number;initialName:string;onClose:()=>void;onGenerated:(url:string)=>void}){
 const {lang}=useI18n(),utils=trpc.useUtils();const labels=lang==='fr'?{title:'Coordonnées de facturation',name:'Nom ou raison sociale',address:'Adresse de facturation complète',country:'Pays (code à deux lettres)',registration:'Immatriculation / SIREN (entreprise)',taxId:'Identifiant TVA (si applicable)',issue:'Émettre la facture',cancel:'Annuler',note:'Vérifiez ces coordonnées : elles seront conservées sur la facture émise.'}:lang==='ar'?{title:'بيانات الفاتورة',name:'الاسم أو الاسم القانوني',address:'عنوان الفوترة الكامل',country:'رمز الدولة من حرفين',registration:'رقم تسجيل الشركة',taxId:'الرقم الضريبي إن وجد',issue:'إصدار الفاتورة',cancel:'إلغاء',note:'تحقق من هذه البيانات؛ سيتم حفظها في الفاتورة الصادرة.'}:{title:'Billing details',name:'Name or legal business name',address:'Full billing address',country:'Country (two-letter code)',registration:'Business registration number',taxId:'VAT identifier, if applicable',issue:'Issue invoice',cancel:'Cancel',note:'Check these details: they will be retained on the issued invoice.'};
 const [language,setLanguage]=useState<InvoiceLanguage>(lang==='ar'?'ar':lang==='en'?'en':'fr');
 const [form,setForm]=useState({name:initialName,address:'',country:'',registration:'',taxId:''});const mutation=trpc.checkout.generateInvoice.useMutation({onSuccess:data=>{utils.dashboard.orders.invalidate();if(data.url)onGenerated(data.url);}});
 return <Dialog open onOpenChange={open=>{if(!open&&!mutation.isPending)onClose();}}><DialogContent><DialogHeader><DialogTitle>{labels.title}</DialogTitle></DialogHeader><p className="text-sm">{labels.note}</p><label className="block text-sm">{lang==='fr'?'Langue du document':lang==='ar'?'لغة المستند':'Document language'}<select className="block w-full border rounded p-2 mt-1" disabled={mutation.isPending} value={language} onChange={e=>setLanguage(e.target.value as InvoiceLanguage)}><option value="fr">Français</option><option value="en">English</option><option value="ar">العربية</option></select></label><p className="text-xs text-muted-foreground">{lang==='fr'?"Les coordonnées, descriptions et mentions restent dans leur langue d’origine.":lang==='ar'?'تبقى البيانات والأوصاف والشروط بلغتها الأصلية.':'Details, descriptions and terms remain in their original language.'}</p>{(['name','address','country','registration','taxId'] as const).map(key=><label key={key} className="block text-sm">{labels[key]}<input disabled={mutation.isPending} value={form[key]} maxLength={key==='address'?1000:key==='country'?2:255} onChange={e=>setForm(v=>({...v,[key]:key==='country'?e.target.value.toUpperCase():e.target.value}))} className="block w-full border rounded p-2 mt-1"/></label>)}{mutation.error&&<p role="alert" className="text-sm">{mutation.error.message}</p>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={mutation.isPending} onClick={onClose}>{labels.cancel}</Button><Button disabled={mutation.isPending||!invoiceBuyerSchema.safeParse(form).success} onClick={()=>mutation.mutate({orderId,buyer:form,language})}>{labels.issue}</Button></div></DialogContent></Dialog>;
}
