import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Button} from '@/components/ui/button';
export default function LiveInstructorHistory({roomType,roomId}:{roomType:'session'|'webinar';roomId:number}){
 const {lang}=useI18n();
 const t=lang==='fr'?{notice:'Les noms affichés sont actuels ; les identifiants de l’instructeur et de l’administrateur sont conservés.',empty:'Aucun changement enregistré depuis la mise en place du journal.',active:'Affectation active',inactive:'Affectation inactive',by:'Par',instructor:'Instructeur',loading:'Chargement…',retry:'Réessayer',older:'Plus ancien',newer:'Plus récent'}:lang==='ar'?{notice:'الأسماء المعروضة حالية؛ يتم الاحتفاظ بمعرفات المدرب والمسؤول.',empty:'لا توجد تغييرات مسجلة منذ إنشاء السجل.',active:'تعيين نشط',inactive:'تعيين غير نشط',by:'بواسطة',instructor:'المدرب',loading:'جار التحميل…',retry:'إعادة المحاولة',older:'أقدم',newer:'أحدث'}:{notice:'Displayed names are current; instructor and administrator identifiers are retained.',empty:'No changes recorded since this journal was introduced.',active:'Active assignment',inactive:'Inactive assignment',by:'By',instructor:'Instructor',loading:'Loading…',retry:'Retry',older:'Older',newer:'Newer'};
 const [cursors,setCursors]=useState<Array<number|undefined>>([undefined]);
 const query=trpc.admin.liveInstructors.history.useQuery({roomType,roomId,before:cursors[cursors.length-1]});
 return <section className="space-y-3 text-sm"><p className="text-muted-foreground">{t.notice}</p>{query.isLoading?<p role="status">{t.loading}</p>:query.error?<div role="alert">{query.error.message}<Button variant="outline" onClick={()=>query.refetch()}>{t.retry}</Button></div>:<>{!query.data?.events.length&&<p>{t.empty}</p>}<ol className="space-y-2">{query.data?.events.map(event=><li key={event.id} className="border rounded p-3 space-y-1"><p>{new Date(event.createdAt).toLocaleString(lang)}</p><p className="font-medium">{t.instructor}: {event.instructorName??'—'} (#{event.userId})</p><p>{event.previousActive?t.active:t.inactive} → {event.active?t.active:t.inactive}</p><p>{t.by} {event.actorName??'—'} (#{event.actorId})</p><p className="whitespace-pre-wrap break-words">{event.reason}</p></li>)}</ol><div className="flex gap-2"><Button variant="outline" disabled={cursors.length<2||query.isFetching} onClick={()=>setCursors(v=>v.slice(0,-1))}>{t.newer}</Button><Button variant="outline" disabled={!query.data?.nextCursor||query.isFetching} onClick={()=>setCursors(v=>[...v,query.data!.nextCursor!])}>{t.older}</Button></div></>}</section>;
}
