import LiveInstructorHistory from "./LiveInstructorHistory";
import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
export default function LiveInstructorsDialog({roomType,roomId,onClose}:{roomType:'session'|'webinar';roomId:number;onClose:()=>void}){
 const {lang}=useI18n(),utils=trpc.useUtils();
 const t=lang==='fr'?{title:'Instructeurs de la classe',notice:'Une affectation active donne la modération de cette classe, sans accès au studio. Un compte instructeur actif est requis. Les administrateurs gardent leur accès.',search:'Rechercher par nom ou email (2 caractères minimum)',assign:'Affecter',remove:'Retirer',restore:'Réaffecter',reason:'Motif',confirm:'Confirmer',cancel:'Annuler',empty:'Aucune affectation enregistrée.',loading:'Chargement…',retry:'Réessayer',active:'Active',inactive:'Inactive'}:lang==='ar'?{title:'مدربو الفصل',notice:'يمنح التعيين النشط الإشراف على هذا الفصل دون الاستوديو. يلزم حساب مدرب نشط. يحتفظ المسؤولون بالوصول.',search:'البحث بالاسم أو البريد (حرفان على الأقل)',assign:'تعيين',remove:'إزالة',restore:'إعادة تعيين',reason:'السبب',confirm:'تأكيد',cancel:'إلغاء',empty:'لا توجد تعيينات مسجلة.',loading:'جار التحميل…',retry:'إعادة المحاولة',active:'نشط',inactive:'غير نشط'}:{title:'Class instructors',notice:'An active assignment grants moderation for this class, without studio access. An active instructor account is required. Administrators retain access.',search:'Search by name or email (at least 2 characters)',assign:'Assign',remove:'Remove',restore:'Reassign',reason:'Reason',confirm:'Confirm',cancel:'Cancel',empty:'No assignments recorded.',loading:'Loading…',retry:'Retry',active:'Active',inactive:'Inactive'};
 const [showHistory,setShowHistory]=useState(false);
 const [search,setSearch]=useState(''),[reason,setReason]=useState(''),[selection,setSelection]=useState<{userId:number;name:string|null;active:boolean}|null>(null);
 const list=trpc.admin.liveInstructors.list.useQuery({roomType,roomId});
 const candidates=trpc.admin.liveInstructors.search.useQuery({search:search.trim()},{enabled:search.trim().length>=2});
 const mutation=trpc.admin.liveInstructors.set.useMutation({onSuccess:()=>{setSelection(null);setReason('');utils.admin.liveInstructors.list.invalidate({roomType,roomId});utils.admin.liveInstructors.history.invalidate();utils.live.access.invalidate({roomType,roomId});}});
 const select=(value:typeof selection)=>{setSelection(value);setReason('');mutation.reset();};
 return <Dialog open onOpenChange={open=>{if(!open&&!mutation.isPending)onClose();}}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{t.title}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{t.notice}</p>
 {list.isLoading?<p>{t.loading}</p>:list.error?<div role="alert">{list.error.message}<Button variant="outline" onClick={()=>list.refetch()}>{t.retry}</Button></div>:<><ul className="space-y-2">{list.data?.map(a=><li key={a.id} className="border rounded p-2 flex justify-between gap-2 text-sm"><span>{a.name??'—'} (#{a.userId}) · {a.active?t.active:t.inactive}{a.role!=='instructor'||a.status!=='active'?` · ${a.role}/${a.status}`:''}</span><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={()=>select({userId:a.userId,name:a.name,active:!a.active})}>{a.active?t.remove:t.restore}</Button></li>)}</ul>{!list.data?.length&&<p>{t.empty}</p>}</>}
 <label htmlFor="instructor-search">{t.search}</label><Input id="instructor-search" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)} disabled={mutation.isPending}/>
 {search.trim().length>=2&&<>{candidates.isLoading&&<p>{t.loading}</p>}{candidates.error&&<p role="alert">{candidates.error.message}</p>}<ul className="space-y-2">{candidates.data?.filter(c=>!list.data?.some(a=>a.userId===c.id&&a.active)).map(c=><li key={c.id} className="flex justify-between gap-2 text-sm"><span>{c.name??'—'} · {c.email??`#${c.id}`}</span><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={()=>select({userId:c.id,name:c.name,active:true})}>{t.assign}</Button></li>)}</ul></>}
 {selection&&<form className="space-y-2 border-t pt-3" onSubmit={e=>{e.preventDefault();mutation.mutate({roomType,roomId,userId:selection.userId,active:selection.active,reason});}}><p>{selection.active?t.assign:t.remove}: {selection.name??'—'} (#{selection.userId})</p><label htmlFor="instructor-reason">{t.reason}</label><Input id="instructor-reason" required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} disabled={mutation.isPending}/>{mutation.error&&<p role="alert">{mutation.error.message}</p>}<div className="flex gap-2"><Button type="submit" disabled={mutation.isPending||reason.trim().length<3}>{t.confirm}</Button><Button type="button" variant="outline" disabled={mutation.isPending} onClick={()=>select(null)}>{t.cancel}</Button></div></form>}
 <Button type="button" variant="outline" aria-expanded={showHistory} onClick={()=>setShowHistory(v=>!v)}>{lang==='fr'?'Historique des affectations':lang==='ar'?'سجل التعيينات':'Assignment history'}</Button>
 {showHistory&&<LiveInstructorHistory roomType={roomType} roomId={roomId}/>}
 </DialogContent></Dialog>;
}
