import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Button} from '@/components/ui/button';
export default function PendingAiOutlines({onCreated}:{onCreated:(id:number)=>void}){
 const {lang}=useI18n(),utils=trpc.useUtils();
 const t=lang==='fr'?{title:'Plans IA à enregistrer',notice:'Retrouvez un plan déjà généré sans nouvel appel IA. Le cours sera créé dans son espace d’origine.',create:'Créer le cours',operator:'Espace opérateur',empty:'Aucun plan en attente.',retry:'Réessayer',older:'Plus ancien',newer:'Plus récent',loading:'Chargement…'}:lang==='ar'?{title:'خطط الذكاء الاصطناعي المحفوظة',notice:'استرجع خطة مولدة دون طلب ذكاء اصطناعي جديد. سيتم إنشاء الدورة في مساحتها الأصلية.',create:'إنشاء الدورة',operator:'مساحة المشغل',empty:'لا توجد خطط معلقة.',retry:'إعادة المحاولة',older:'أقدم',newer:'أحدث',loading:'جار التحميل…'}:{title:'Saved AI outlines',notice:'Recover an existing outline without a new AI call. The course will be created in its original workspace.',create:'Create course',operator:'Operator workspace',empty:'No pending outlines.',retry:'Retry',older:'Older',newer:'Newer',loading:'Loading…'};
 const [cursors,setCursors]=useState<Array<number|undefined>>([undefined]);
 const query=trpc.maker.pendingAiOutlines.useQuery({before:cursors[cursors.length-1]},{refetchInterval:30000});
 const mutation=trpc.maker.createFromAiOutline.useMutation({onSuccess:r=>{utils.maker.pendingAiOutlines.invalidate();utils.maker.courses.invalidate();onCreated(r.trainingId);}});
 return <details className="border rounded p-2 mb-3 text-xs"><summary className="cursor-pointer font-semibold">{t.title}</summary><div className="space-y-2 mt-2"><p>{t.notice}</p>{query.isLoading?<p>{t.loading}</p>:query.error?<div role="alert">{query.error.message}<Button size="sm" variant="outline" onClick={()=>query.refetch()}>{t.retry}</Button></div>:<>{!query.data?.entries.length&&<p>{t.empty}</p>}<ul className="space-y-2">{query.data?.entries.map(row=><li key={row.id} className="border rounded p-2 space-y-1"><p className="font-medium">{row.title}</p><p>{row.organizationName??t.operator} · {new Date(row.createdAt).toLocaleString(lang)}</p><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={()=>mutation.mutate({id:row.id})}>{t.create}</Button></li>)}</ul>{(cursors.length>1||query.data?.nextCursor)&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={cursors.length<2||query.isFetching} onClick={()=>setCursors(v=>v.slice(0,-1))}>{t.newer}</Button><Button size="sm" variant="outline" disabled={!query.data?.nextCursor||query.isFetching} onClick={()=>setCursors(v=>[...v,query.data!.nextCursor!])}>{t.older}</Button></div>}</>}{mutation.error&&<p role="alert">{mutation.error.message}</p>}</div></details>;
}
