import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useI18n} from '@/i18n';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
export default function WebinarHistoryDialog({id,onClose}:{id:number;onClose:()=>void}){
 const {lang}=useI18n();
 const text=lang==='fr'?{heading:'Historique du webinaire',notice:'Les noms des auteurs sont leurs noms actuels. Les dates sont affichées dans votre fuseau local.',empty:'Aucun événement enregistré depuis la mise en place du journal.',loading:'Chargement…',retry:'Réessayer',older:'Plus ancien',newer:'Plus récent',before:'Avant',after:'Après',created:'Création',rescheduled:'Horaires',metadata:'Informations et places',status:'Statut',title:'Titre',description:'Description',scheduledAt:'Début',durationMinutes:'Durée (min)',maxParticipants:'Places',trainingId:'Formation',unlimited:'Sans limite',scheduled:'Planifié',live:'En direct',completed:'Terminé',cancelled:'Annulé'}:lang==='ar'?{heading:'سجل الندوة',notice:'أسماء المؤلفين المعروضة حالية. تعرض التواريخ في توقيتك المحلي.',empty:'لا توجد أحداث مسجلة منذ إنشاء السجل.',loading:'جار التحميل…',retry:'إعادة المحاولة',older:'أقدم',newer:'أحدث',before:'قبل',after:'بعد',created:'إنشاء',rescheduled:'المواعيد',metadata:'المعلومات والمقاعد',status:'الحالة',title:'العنوان',description:'الوصف',scheduledAt:'البداية',durationMinutes:'المدة (دقيقة)',maxParticipants:'المقاعد',trainingId:'الدورة',unlimited:'غير محدود',scheduled:'مجدول',live:'مباشر',completed:'مكتمل',cancelled:'ملغى'}:{heading:'Webinar history',notice:'Displayed actor names are current. Dates use your local time zone.',empty:'No events recorded since this journal was introduced.',loading:'Loading…',retry:'Retry',older:'Older',newer:'Newer',before:'Before',after:'After',created:'Created',rescheduled:'Schedule',metadata:'Details and seats',status:'Status',title:'Title',description:'Description',scheduledAt:'Start',durationMinutes:'Duration (min)',maxParticipants:'Seats',trainingId:'Course',unlimited:'Unlimited',scheduled:'Scheduled',live:'Live',completed:'Completed',cancelled:'Cancelled'};
 const [cursors,setCursors]=useState<Array<number|undefined>>([undefined]);
 const query=trpc.admin.webinars.history.useQuery({id,before:cursors[cursors.length-1]});
 const fields=['title','description','scheduledAt','durationMinutes','maxParticipants','status','trainingId'] as const;
 const value=(field:typeof fields[number],v:string|number|null|undefined)=>v==null?(field==='maxParticipants'&&v===null?text.unlimited:'—'):field==='scheduledAt'?new Date(String(v)).toLocaleString(lang):field==='status'&&['scheduled','live','completed','cancelled'].includes(String(v))?text[v as 'scheduled']:String(v);
 return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{text.heading}{query.data?` — ${query.data.webinar.title}`:''}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{text.notice}</p>
 {query.isLoading?<p role="status">{text.loading}</p>:query.error?<div role="alert">{query.error.message}<Button onClick={()=>query.refetch()} variant="outline">{text.retry}</Button></div>:<>
 {!query.data?.events.length&&<p>{text.empty}</p>}
 <ol className="space-y-4">{query.data?.events.map(event=><li key={event.id} className="border rounded p-3 text-sm space-y-2"><p className="font-semibold">{text[event.action as 'created']??event.action} · {new Date(event.createdAt).toLocaleString(lang)}</p><p>{event.actorName??'—'} (#{event.actorId})</p><div className="overflow-x-auto"><table className="w-full table-fixed"><thead><tr><th></th><th className="text-start">{text.before}</th><th className="text-start">{text.after}</th></tr></thead><tbody>{fields.filter(field=>!event.previous||event.previous[field]!==event.next[field]).map(field=><tr key={field} className="border-t align-top"><th className="text-start p-1">{text[field]}</th><td className="p-1 whitespace-pre-wrap break-words">{value(field,event.previous?.[field])}</td><td className="p-1 whitespace-pre-wrap break-words">{value(field,event.next[field])}</td></tr>)}</tbody></table></div>{event.action!=='created'&&<p className="whitespace-pre-wrap break-words">{event.reason}</p>}</li>)}</ol>
 <div className="flex gap-2"><Button variant="outline" disabled={cursors.length<2||query.isFetching} onClick={()=>setCursors(v=>v.slice(0,-1))}>{text.newer}</Button><Button variant="outline" disabled={!query.data?.nextCursor||query.isFetching} onClick={()=>setCursors(v=>[...v,query.data!.nextCursor!])}>{text.older}</Button></div></>}
 </DialogContent></Dialog>;
}
