export const cockpitCopy = {
  fr: {
    eyebrow: "R-AERO · L’AVIATION S’APPREND AUTREMENT",
    title: "Entrez dans",
    accent: "votre prochain niveau.",
    intro:
      "Du cockpit à votre prochaine certification. Une nouvelle façon de se former, de transmettre et de faire grandir son équipe.",
    enter: "Entrez dans le cockpit",
    scroll: "Faites défiler pour embarquer",
    explore: "Explorez le cockpit",
    views: [
      "Vue extérieure",
      "Au poste",
      "Instruments",
      "Console centrale",
      "Panneau supérieur",
    ],
    notes: [
      "L’expertise commence par la curiosité.",
      "Changez de perspective. Prenez votre place.",
      "Comprendre les systèmes. Renforcer ses connaissances.",
      "Des gestes précis. Des compétences qui évoluent.",
      "Explorez les détails. Gardez une vue d’ensemble.",
    ],
    loading: "Préparation de votre embarquement",
    unavailable: "La visite 3D est indisponible sur cet appareil.",
    retry: "Relancer la visite",
    continueTour: "Continuez à faire défiler pour découvrir la suite.",
    skip: "Passer aux formations",
  },
  en: {
    eyebrow: "R-AERO · A NEW PERSPECTIVE ON AVIATION TRAINING",
    title: "Step into",
    accent: "your next level.",
    intro:
      "From the cockpit to your next certificate. A new way to learn, share expertise and develop your team.",
    enter: "Enter the cockpit",
    scroll: "Scroll to step aboard",
    explore: "Explore the cockpit",
    views: [
      "Exterior",
      "Flight deck",
      "Instruments",
      "Centre console",
      "Overhead panel",
    ],
    notes: [
      "Expertise starts with curiosity.",
      "Change your perspective. Take your place.",
      "Understand the systems. Build your knowledge.",
      "Precise actions. Skills that keep evolving.",
      "Explore the details. Keep the bigger picture.",
    ],
    loading: "Preparing your boarding",
    unavailable: "The 3D visit is unavailable on this device.",
    retry: "Retry the visit",
    continueTour: "Keep scrolling to discover the next view.",
    skip: "Skip to training",
  },
  ar: {
    eyebrow: "R-AERO · منظور جديد للتدريب على الطيران",
    title: "ادخل إلى",
    accent: "مستواك التالي.",
    intro:
      "من قمرة القيادة إلى شهادتك التالية. طريقة جديدة للتعلّم ونقل الخبرة وتطوير فريقك.",
    enter: "ادخل قمرة القيادة",
    scroll: "مرّر للصعود إلى الطائرة",
    explore: "استكشف قمرة القيادة",
    views: [
      "من الخارج",
      "قمرة القيادة",
      "الأجهزة",
      "الكونسول الأوسط",
      "اللوحة العلوية",
    ],
    notes: [
      "تبدأ الخبرة بالفضول.",
      "غيّر منظورك. خذ مكانك.",
      "افهم الأنظمة وطوّر معرفتك.",
      "حركات دقيقة ومهارات تتطور.",
      "استكشف التفاصيل وحافظ على الرؤية الشاملة.",
    ],
    loading: "جارٍ التحضير للصعود",
    unavailable: "الجولة ثلاثية الأبعاد غير متاحة على هذا الجهاز.",
    retry: "أعد المحاولة",
    continueTour: "تابع التمرير لاكتشاف المنظر التالي.",
    skip: "انتقل إلى الدورات",
  },
};
